-- phpMyAdmin SQL Dump
-- version 3.2.4
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Dec 23, 2010 at 12:09 PM
-- Server version: 5.1.44
-- PHP Version: 5.3.1

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `Cart2Mobile_Database`
--

-- --------------------------------------------------------

--
-- Table structure for table `Children_Category`
--

CREATE TABLE IF NOT EXISTS `Children_Category` (
  `item_Name` varchar(255) NOT NULL,
  `Field_Name` varchar(255) NOT NULL,
  PRIMARY KEY (`item_Name`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `Children_Category`
--

INSERT INTO `Children_Category` (`item_Name`, `Field_Name`) VALUES
('Geox JOCKER - Halbschuh - oliv', 'Shoes'),
('Ej Sikke Lej PLAYSUIT - Romper suits - black', 'Clothes');

-- --------------------------------------------------------

--
-- Table structure for table `Children_Clothes`
--

CREATE TABLE IF NOT EXISTS `Children_Clothes` (
  `item_Name` varchar(255) NOT NULL,
  `item_Description` text NOT NULL,
  `item_Price` double NOT NULL,
  `rating_Value` int(11) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `Children_Clothes`
--

INSERT INTO `Children_Clothes` (`item_Name`, `item_Description`, `item_Price`, `rating_Value`) VALUES
('Ej Sikke Lej PLAYSUIT - Romper suits - black', 'Details for Ej Sikke Lej PLAYSUIT - Romper suits - black\r\n\r\nCuddly soft: the black overalls of PLAYSUIT Ej Sikke Lej. Made of soft and warming fleece, is the cute Overall the ideal companion for cool expectant days. With expandable color-contrasting cuffs for optimum fit and a wide collar and handy zip-chin offers protection for the soft PLAYSUIT everything you need for babies. The cute design is determined by a blue owl on the back and also blue elements. Sugar sweet companion: the black overalls of PLAYSUIT Ej Sikke Lej.\r\n\r\nZipper for chin protection\r\npretty hip bags\r\nCare instructions: Wash at 40 c\r\nInseam: 20 cm for size 68\r\nMaterial Outer: 100% polyester\r\nModel: EJ2-jzw-0024-99', 135.6, 0),
('hey woops by bjorkvin GERRITH - Romper - Grey melange', 'Details for Hey woops by bjorkvin GERRITH - Romper - gray melange\r\n\r\nThe gray romper GARRITH by hey woops by bjorkvin - for babies with style! Highly permeable the gray romper from hey woops by bjorkvin comes with the grass-green front print. The gray cotton romper can be compressed with a curved button placket unbuttoned completely and therefore ensures easy on and off. GARRITH comes with dark gray borders and elastic quality thanks to its super comfortable to wear. For sleeping or playing at home: the gray romper GARRITH of hey by bjorkvin woops!\r\n\r\nend button\r\ntransparent front-Print\r\nCare instructions: machine wash at 30 c, not suitable dryer\r\nModel Length: 71 cm for size 86\r\nMaterial Outer: 100% cotton\r\nModel: HE1-LZW 0002-99', 270, 0),
('Kanz Body - Gifts for the birth - classic blue', 'Details for Kanz Body - Gifts for the birth - classic blue\r\n\r\nCozy Body for cuddly hours! The blue body of Kanz impresses with its soft material and a nice color. located on the great blue to brown and white stripes and a cute embroidery on the front. There is also a Shirt for wearing underneath, so baby does not make the weather is cold. Buttons on the body and supports the round neckline of the top allow easy on and off. For babies only soft cozy - the blue body of Kanz!\r\n\r\nsoft material\r\nLong Sleeve\r\nModel Length: 42 cm in size 50\r\nMaterial Outer: Shirt: 80% cotton, 20% polyester, Body: 100% cotton\r\nModel: KA7-jzw-0001-99', 100, 0),
('hey woops by bjorkvin GALATHEA - Body - light blue', 'Details for Hey woops by bjorkvin GALATHEA - Body - light blue\r\n\r\nThe blue body of GALATHEA hey woops by bjorkvin - for trendy guys! I-Pod with a funny little men on the front of the body of cute hey woops by bjorkvin comes in blue. The cotton body can step in and close to the shoulder with practical press studs, thus ensuring a trouble on and off. The dark blue trim at round neck and cut legs complete the look of boyish GALATHEA. Extremely cool: bjorkvin the blue body of GALATHEA woops by hey!\r\n\r\nSnaps in the crotch and on the shoulder\r\ntransparent front-Print\r\nCare instructions: machine wash at 30 c, not suitable dryer\r\nModel Length: 46 in size 86\r\nMaterial Outer: 100% cotton\r\nModel: HE1-LZW 0004-99', 145, 0),
('Ej Sikke Lej ROCKET - Body - Blue', 'Details for Ej Sikke Lej ROCKET - Body - Blue ROCKET - Body - Blue\r\n\r\nLong-sleeved galactic ROCKET by The printed rockets and stars will accompany your child in his dreams. The light blue cuffs complete the design available to guests. Practical snaps in the crotch and neck to ease entry and exit. Particularly important: the soft cotton fabric provides a comfortable fit. Dress up and feel: the blue body of ROCKET \r\n\r\npractical push-buttons\r\nCare instructions: Wash at 40 c\r\nMaterial Outer: 100% cotton\r\nModel: EJ2-jzw-0029-99\r\n', 125, 0),
('Petit Bateau Romper - lait colonel', 'Petit Bateau romper for details - lait / colonel\r\n\r\nFor small sailor - the cute rompers by the French brand Petit Bateau quality with white and blue stripes! So feel of quality: The finely knit romper from Petit Bateau is equipped with an extra soft lining that keeps warm and does not scratch. Two buttons on the neck and legs inside the Downs easier dressing and the wound. For small strip of mice - the new romper from Petit Bateau in blue and white stripes!\r\n\r\nDowns inner legs\r\n2 buttons at the neckline\r\nsoft lining\r\nCare instructions: machine wash 40 c\r\nModel Length: 77 cm for size 86\r\nMaterial Outer: 99% cotton, 1% elastane\r\nModel: PE6-LZW 0032-99', 170, 0);

-- --------------------------------------------------------

--
-- Table structure for table `Children_Shoes`
--

CREATE TABLE IF NOT EXISTS `Children_Shoes` (
  `item_Name` varchar(255) NOT NULL,
  `item_Description` text NOT NULL,
  `item_Price` double NOT NULL,
  `rating_Value` int(11) NOT NULL,
  PRIMARY KEY (`item_Name`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `Children_Shoes`
--

INSERT INTO `Children_Shoes` (`item_Name`, `item_Description`, `item_Price`, `rating_Value`) VALUES
('Geox JOCKER - Halbschuh - oliv', 'Details for Geox Jock - shoe - olive\r\n\r\nThe shoe Jock Oliv Geox - breathable! The athletic shoe for girls from a leather-fabric combination is equipped with patented, Geox breathable rubber sole. The perforated liner made of genuine leather is coated with a waterproof and breathable membrane - all these components together provide a balanced and healthy foot climate. Hook and loop fasteners allow for easy entry. The slip-resistant sole is on the sides, pulled up in front and rear and gives the shoe a sporty, casual look. The color purple is found also in the form of beautiful embroidered logos on the outside and on the velcro strap. The soft inner lining is comfortable and the perfect basis for typical childhood activities such as running, playing and climbing. Sporty all-day shoe for girls - olive shoe from Geox JOCK!\r\n\r\nVelcro fastener\r\nnon-slip soles\r\nInsole: Textile\r\nLining: 100% polyester\r\nSole: Abrasion-resistant rubber\r\nUpper: Leather / Synthetic\r\nModel: GE1-KZW-0054-99', 199.5, 5),
('FROG Robeez - baby shoes - sand', 'Details for Robeez Frog - Baby shoes - sand\r\n\r\nFROG Robeez, ideal for small hoppers and those who want to become! This baby shoe convinced visually with its great location, but also functional. The flexible shaft collar with elastic band allows for a perfect fit and lets the baby-foot slip easily. In addition, FROG is made of genuine leather and, with the sole suede non-slip grip guarantees in the first steps. Robeez is a very versatile and suitable for every day to their first steps to accompany small children: Note Both children''s feet should be measured every 3 months! Robeez are the shoe sizes in months. Here you will find the conversion of the company Robeez in the usual children''s sizes -. 0 6 months size. 17-18 foot length of 118 mm 6 - 12 months size. 19-20 foot length 132 mm 12 - 18 months size. 21-22 foot length 145 mm 18 - 24 months size. 23-24 foot length 153 mm\r\n\r\nOutsole made of genuine suede\r\nShaft collar with elastic band\r\nInsole: Leather\r\nLining: 100% leather\r\nHeight: 28 cm\r\nLength: 37 cm\r\nSole: Genuine Leather\r\nUpper: Leather\r\nWidth: 11 cm\r\nWidth: 3.2 cm\r\nItem number: RO1-k33-0009-03', 136.8, 0),
('LYRICAL Robeez T Strap - brown - Baby Shoe', 'Details for Robeez LYRICAL T STRAP - brown - Baby Shoe\r\n\r\nLYRICAL T STRAP is a very soft baby shoes for girls. Ideal for those first steps convinced that high quality shoe with its floral prints and the small loop. The flexible shaft collar with elastic band allows for a perfect fit and lets the baby-foot slip easily. Both regard children''s feet should be measured approximately every 3 months! Robeez are the shoe sizes in months. Here you will find the conversion of the company Robeez in the usual children''s sizes -. 0 6 months size. 17-18 foot length of 118 mm 6 - 12 months size. 19-20 foot length 132 mm 12 - 18 months size. 21-22 foot length 145 mm 18 - 24 months size. 23-24 foot length 153 mm\r\n\r\nOutsole made of genuine suede\r\nShaft collar with elastic band\r\nInsole: Leather\r\nLining: 100% leather\r\nSole: Genuine Leather\r\nUpper: Leather\r\nItem number: RO1-k33-0037-13', 290, 5),
('Adidas STAN SMITH ADIKIDS CRI - Baby Shoes Cormag', 'Details for Adidas STAN SMITH ADIKIDS CRI - Baby Shoes Cormag\r\n\r\nThe brand-new sneakers STAN SMITH ADIKIDS CRI made by Adidas - absolutely KIDS STYLE! This sneaker will give your child the degree of coolness. The Velcro allows quick and easy on and off. The soft padding ensures that the feet of the small ones are protected at all times. The beautiful color combination shows that it is not cool style may be too young!\r\n\r\nnon-slip sole\r\nAdidas logo on the heel\r\nInsole: Textile\r\nLining: 100% polyester\r\nSole: Abrasion-resistant rubber\r\nUpper: Leather\r\nModel: AD1-K05-0126-12', 135, 5),
('Living Kitzbuhel Baby Shoes - red', 'Ahoy! Living Kitzbuhel offers this shoe a wonderfully playful design with sail boat applications! The durable upper in a rich shade of red is accompanied by small Blockkaros that provide a very realistic look! The lightweight model is quite straightforward to include a Velcro closure. An elastic band is revised under the tongue ensures dimensional stability. Ahoy for the shoe of Living Kitzbuhel!\r\n\r\nVelcro fastener\r\nslightly molded sole\r\nInsole: Textile\r\nLining: 100% polyester\r\nSole: high quality plastic\r\nUpper: textile\r\nModel: LI2-KZA 0203-05', 225, 0),
('ecco MIMIC - Shoes - Purple', 'In shimmering violet come MIMIC, hence the new shoes from Ecco. The whole shoe is made of soft leather and the laces can be adjusted to suit the Babyfu. On the side of the perforations in beautiful silver sparkle. The outsole shows by the profile that the foot is in front extra wide and designed by the Babyfu sufficient space. Little princesses quite large - with MIMIC, the purple loafers from Ecco!\r\n\r\n4-hole lacing\r\nshimmering surface\r\nInsole: Leather\r\nLining: 100% leather\r\nSole: high quality plastic\r\nUpper: Leather\r\nModel: EC1-KZW-0125-99', 125, 0),
('Adelaide GLUCKSPILZ - Baby Shoes - Plaid Blue', 'Details for Adelaide GLUCKSPILZ - Baby Shoes - Plaid Blue\r\n\r\nSo your baby can be guaranteed GLUCKSPILZ - with the new baby shoe from Adelaide in the blue plaid! Manufactured from textile baby shoe is very soft and fits perfectly to the small foot. In addition, the entire shoe lined with wool and has so wonderfully warm. The outsole is soft and very flexible. Absolute eye catcher is the mushroom-application with the typical slogan GLUCKSPILZ Adelaide. Simply sweet as sugar - the new baby shoe GLUCKSPILZ of Adelaide in the blue plaid!\r\n\r\nwarm lining\r\nVelcro fastener\r\nInsole: wool\r\nLining: 100% wool\r\nSole: Genuine Leather\r\nUpper: textile\r\nModel: AD2-KZW 0005-99', 192, 0),
('Kickers SWEET - Baby Shoes - Bordeaux', 'Details for Kickers SWEET - Baby Shoes - Bordeaux\r\n\r\nThe red walker shoe from Kickers SWEET - for baby''s first steps! The soft suede and the soft non-slip sole, which is pulled up the front and rear and provides shock resistance, make every step a breeze. The loud SWEET walker shoe from Kickers is not only comfortable, but pulls through his red-pink-orange design also all the attention. Simply sweet as sugar - the red walker shoe from Kickers SWEET!\r\n\r\nnon-slip rubber sole\r\nLeather lining\r\nInsole: Leather\r\nLining: 100% leather\r\nSole: high quality plastic\r\nUpper: Leather\r\nModel: KI1-KZW-0013-99', 199, 0);

-- --------------------------------------------------------

--
-- Table structure for table `Items_Comments`
--

CREATE TABLE IF NOT EXISTS `Items_Comments` (
  `item_Name` varchar(255) NOT NULL,
  `Customer_Name` varchar(255) NOT NULL,
  `item_Comments` text NOT NULL,
  `Quality` int(11) NOT NULL,
  `Comfort` int(11) NOT NULL,
  `Appearance` int(11) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `Items_Comments`
--

INSERT INTO `Items_Comments` (`item_Name`, `Customer_Name`, `item_Comments`, `Quality`, `Comfort`, `Appearance`) VALUES
('Guess STELLAR HOODIE - Sweat Jacket - Brown', 'Katja', 'A real eye-catcher\r\nVery chic, yet comfortable jacket. Is it worth something special, and the money anyway.', 4, 2, 5),
('DEPT ANIMAL FLOWER - Sweatshirt - dusty olive', 'Anonymous ', 'Class\r\nBeautiful sweatshirt from very soft material, I like it in kind even better than the pictures. The price is of course not just low, but you also get something special that not every second with on the road.', 5, 5, 5),
('Bjorkvin PARIS-Hoody - Grey melange', 'Nicole', 'Good cut!\r\nBeautiful sweater! Snug around. Shaped fitting with trademark pressure.', 5, 5, 5),
('Bjorkvin PARIS-Hoody - Grey melange', 'Anonymous', 'warm and pleasant!\r\nVery nice hoody, suitable for the first cold days! I ordered M & L, I have decided for L.', 5, 5, 3),
('The North Face GRIT STONE - Jacket - Asphalt Grey', 'Anonymous', 'Great jacket\r\nGreat jacket! Practice and the zipper on the button bar. I''m very satisfied!', 5, 5, 5),
('Selected Homme STEVEN - jacket - black', 'Gina', 'Great jacket\r\nGreat jacket! Practice and the zipper on the button bar. I''m very satisfied!', 5, 5, 5),
('Billabong Biwo - sweatshirt - black', 'Bery Barth', 'The favorite sweatshirt of my granddaughter\r\nThis shirt is just great. My granddaughter has already seen on holiday in Spain, but unfortunately it was no longer available in our city. As luck would have it I''ve found on Zalando. The shirt is super and has roundly earned five stars and another five stars for the bright eyes of my grandchild.', 5, 5, 5),
('Selected Homme STEVEN - jacket - black', 'Isabella Glombik', 'Cool College Jacket\r\nGreat jacket! Fits great for jeans or chino!', 5, 5, 5),
('Esprit shirt - black', 'Catharina hero', 'Fits on all occasions\r\nI can think of this article can wear for every occasion. Is also very comfortable and stay warm.', 3, 4, 5),
('ESPRIT Collection Longtop - grey', 'Anonymous', 'Toll\r\nVery nice top!', 5, 5, 5),
('Desigual Shirt - Multicolor', 'Radegund Mari', 'Desigual Shirt\r\nGreat shirt', 5, 5, 5),
('Vero Moda NEW RATLI LS V-NECK - shirt - white', 'Sabrina', 'Very nice\r\nNice basic shirt - a reasonable price.', 5, 5, 5),
('Coffee Shirt - steel melange', 'Petra Randelshofer', 'Beautifully exactly as described\r\nBeautifully had accurately described how surprised and pleased how it all fitted hat!', 5, 5, 5),
('LTB VALERIE RIVIERA - jeans - denim', 'Miley Ray Cyrus', 'Perfect fit?\r\nrather less unusual than expected', 5, 5, 5),
('Pepe Jeans BOOTCUT JOULE X67 - jeans - medium shade', 'Catharina hero', 'Super Jeans\r\nI ordered these jeans in 26/34 and she was in a bunch too far. A small number in 25/34 they fit perfectly. Can I recommend you only!', 5, 5, 5),
('Pepe Jeans BOOTCUT JOULE X67 - jeans - medium shade', 'Angela Leeb ', 'I may well hipsters, but this sits best trozt Pepe quality at my deep:)', 5, 3, 4),
('Mavi Olivia - Jeans - deep cool', 'Heike Beck', 'The pants super sits and flatters the figure. However, the length 34 is not very long, but enough for me made yet. The washing is somewhat different in the picture.', 5, 5, 5),
('Geox JOCKER - Halbschuh - oliv', 'Anonymous', 'We ordered the shoes for our daughter and she finds it great. The best thing for them was of course the flashing of the occurrence. We can only say - GEOX quality - just super.', 5, 5, 5),
('Geox JOCKER - Halbschuh - oliv', 'Sabine ', 'As usual from Geox!\r\nThe shoes are what I''m used to from Geox, qualitaitv very well and also fall as usual from the sneakers by Geox something smaller. But that''s ok, if you know it. My daughter loves the brick on the sides, which blink when she jumps. I would buy the shoes at any time.', 5, 5, 5),
('LYRICAL Robeez T Strap - brown - Baby Shoe', 'Anonymous', 'Super\r\nVery good alternative to the "normal" baby walker shoes', 5, 5, 5),
('Adidas STAN SMITH ADIKIDS CRI - Baby Shoes Cormag', 'Catharina hero', 'Cute Baby Shoes\r\nIs very nice. Adidas is generally rather small.', 5, 4, 5);

-- --------------------------------------------------------

--
-- Table structure for table `Mens_Category`
--

CREATE TABLE IF NOT EXISTS `Mens_Category` (
  `item_Name` varchar(255) NOT NULL,
  `Field_Name` varchar(255) NOT NULL,
  PRIMARY KEY (`Field_Name`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `Mens_Category`
--

INSERT INTO `Mens_Category` (`item_Name`, `Field_Name`) VALUES
('Jack & Jones', 'Shirts'),
('Wrangler CRANK', 'Jeans'),
('Bench ALTERED HOODY', 'Jackets'),
('Replay Chino', 'Pants');

-- --------------------------------------------------------

--
-- Table structure for table `Mens_Jackets`
--

CREATE TABLE IF NOT EXISTS `Mens_Jackets` (
  `item_Name` varchar(255) NOT NULL,
  `item_Description` text NOT NULL,
  `item_Price` float NOT NULL,
  `rating_Value` int(11) NOT NULL,
  PRIMARY KEY (`item_Name`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `Mens_Jackets`
--

INSERT INTO `Mens_Jackets` (`item_Name`, `item_Description`, `item_Price`, `rating_Value`) VALUES
('Bench DISGRACE - jacket - black', 'Details for Bench DISGRACE - jacket - black\r\nBench proves the DISGRACE jacket in black again for style. With hood and collar and a double zip at the neck, the warm jacket makes her look and genuine in terms of functionality something. Thanks to the side pockets on the stomach must not freeze the hands. Withstand wind and weather - with the stylish Bench jacket in black DISGRACE!\r\n\r\nHooded Double-zip at the collar Slanted pockets on the stomach Elasticated hem\r\nCare instructions: machine wash at 30 degrees, not suitable dryer\r\nLength: Medium\r\nFit: Normal\r\nFilling material: 100% polyester\r\nModel Length: 73 cm in size M\r\nSleeve length: 70 cm in size M\r\nMaterial Outer: 60% cotton, 40% polyamide\r\nModel: BE6-xzw-0152-99', 100, 0),
('Khujo ARTHUR HERRINGBONE - Jacket - Black Grey', 'Details for Khujo ARTHUR HERRINGBONE - Jacket - Black Grey\r\n\r\nDeft mix of casual jacket and knit sweaters applications! The new ARTHUR HERRINGBONE jacket in black / gray magic in the house khujo at first sight. The knitted hood can be virtually separated out with a zipper and the jacket-like jacket can be worn solo. Two buttons and patch pockets complete the design of the great Arthur HERRINGBONE jacket khujo.\r\n\r\ndetachable zippered knitting pplications\r\npatch pockets\r\nLining: 100% polyester\r\nCare Instructions: Cleaning\r\nLength: Medium\r\nFit: Normal\r\nModel Length: 75 cm in size M\r\nSleeve length: 67 cm in size M\r\nMaterial Outer: 50% wool, 40% viscose, 10% polyester\r\nModel: KH1-xzw-0033-99', 112, 0),
('Adidas HARRINGT - Jacket - black & iron', 'Details for Adidas HARRINGT - Jacket - black / iron\r\n\r\nHARRINGT Jacket in Black by Adidas - Athletic, but for everyday use! With the black jacket from the Adidas Originals Series A.039 overlooking the trendy label once again back to its great tradition. HARRINGT presented with a classic collar, two slanted side pockets with button closure and a gaudy blue lining. Elastic cuffs on sleeves and hem ensure a perfect fit and ensure that the black jacket from Adidas HARRINGT not want to take off so fast!\r\n\r\n2 buttons at the collar inside pocket\r\nCare instructions: Wash at 30 degrees, not suitable dryer\r\nLength: Medium\r\nFit: Normal\r\nFilling material: 100% polyester\r\nModel Length: 70 cm in size M\r\nSleeve length: 69 cm in size M\r\nMaterial Outer: 100% cotton\r\nModel: AD122D00A-802', 117.6, 0),
('brown - esprit leather jacket', 'Details for Esprit leather jacket - brown\r\n\r\nClassic, cool and masculine: the brown leather jacket from Esprit! From very soft sheep leather is this piece of jewelry that acts with his pockets and high neck incomparably translucent. The hands can be easily put into the pockets, and the small collar is nestled comfortably at the neck. They would never take them off: the leather jacket from Esprit in brown!\r\n\r\nFour patch pockets\r\ntwo pockets for your hands\r\nInside pocket\r\nZipper and snaps\r\nStand-up collar with ribbed cuffs\r\nSoft sheepskin\r\nLining: 100% cotton\r\nCare instructions: Leather Cleaning\r\nLength: Medium\r\nFit: Normal\r\nModel Length: 73 cm in size M\r\nSleeve length: 66 cm in size M\r\nMaterial Outer: 100% leather\r\nArticle ID: ES1-xzw-0152-99', 152, 0),
('The North Face GRIT STONE - Jacket - Asphalt Grey', 'Details for The North Face GRIT STONE - Jacket - Asphalt Grey\r\n\r\nThe ultimate outdoor jacket - GRIT STONE in Grey The North Face. All products of the Summit Series and that includes this jacket were developed under extreme weather and terrain conditions and offer high performance. This jacket keeps you warm, but weighs almost nothing. It is windproof, water repellent, stretchable and breathable. For participants - the jacket GRIT STONE in Grey The North Face!\r\n\r\nHand feed engaging Bag: 100% polyester\r\nBiceps pocket lining: 85% Nylon, 15% spandex\r\nwind-and waterproof\r\nBreathable\r\nCare instructions: Wash at 40 degrees\r\nLength: Medium\r\nFit: Normal\r\nModel Length: 73 cm in size M\r\nSleeve length: 67 cm in size M\r\nMaterial Outer: 84% polyester, 16% spandex\r\nModel: TH3-xzw-0049-99', 125, 5),
('Selected Homme MOUNTAIN XC - Winter Jacket - Twilight Blue', 'Details for Selected Homme MOUNTAIN XC - Winter Jacket - Twilight Blue\r\n\r\nFirst choice this winter - the blue winter jacket MOUNTAIN XC Selected Homme! With hood and warming collar one is perfectly equipped for cold days. But should not this cool design will be ignored: Stylish bags falling on front and sleeves to convince the eye and skillfully anyone who wants to look even on cold days, cool and casual. Stylish through the winter - with the blue winter jacket MOUNTAIN XC Selected Homme!\r\n\r\nDetachable hood with detachable fur trim in addition\r\nZip and button closure\r\nmany useful pockets\r\nCare instructions: Wash at 30 degrees\r\nLength: Medium\r\nFit: Normal\r\nMaterial Filling: 80% down, 20% feathers\r\nModel Length: 81 cm in size M\r\nSleeve length: 61 cm in size M\r\nMaterial Outer: 100% Nylon\r\nModel: SE622D004-502', 192, 0),
('Ellesse MUNDIAL REPLIS - jacket - light blue', 'Details for Ellesse MUNDIAL REPLIS - jacket - light blue\r\n\r\nRetro fans take note - here comes the bright blue jacket MUNDIAL REPLIS by Ellesse, inspired by the ski fashions of the 70s. Equipped with a light, soft filling, it is ideal for the transition period and keep warm. Two outside pockets, a zipper pocket inside, a buttoned collar with drawstring, finished the ideal companion throughout the day. Looks good and keeps warm - the light blue jacket MUNDIAL REPLIS with dark blue stripes from Ellesse.\r\n\r\n2 pockets outside\r\nZipper pocket inside\r\nbuttoned collar with tie\r\nLining: 100% polyamide\r\nCare instructions: machine wash at 30 degrees, not suitable dryer\r\nLength: Long\r\nFit: Normal\r\nFilling material: 100% polyester\r\nModel Length: 75 cm in size M\r\nSleeve length: 65 cm in size M\r\nMaterial Outer: 100% polyamide\r\nModel: EL922D001-501', 117.6, 0),
('Adidas SPO FB TT - Jacket - white & dark indigo', 'Details for Adidas SPO FB TT - Jacket - white / dark indigo\r\n\r\nLet''s go Retro! The SPO FB TT can track jacket from Adidas is wind down and unwinding. The soft material provides a high wearing comfort and the side pockets you can store a lot. The orange strip is a great and colorful detail, especially the SPO FB TT track jacket from Adidas!\r\n\r\nKnitted cuffs\r\nSide pockets with zipper\r\nLogo and football embroidery\r\nFit: Normal\r\nModel length: 69cm in size M\r\nMaterial Outer: 100% polyester\r\nModel: AD4-xzw 0010-99', 192, 0),
('Esprit Winter Jacket - black', 'Details for Esprit Winter Jacket - black\r\n\r\nWinter jacket in black from Esprit. When it gets really cold, it must be this smart jacket. With her warm padding keeps the cold effectively away from us. The nylon upper has also had bad weather, and thanks to the many pockets inside and outside the jacket is also extremely practical. Our tip: winter jacket in black from Esprit.\r\n\r\nDetachable hood\r\nPlus additional zipper placket\r\nCare instructions: Wash at 40 degrees\r\nLength: Long\r\nFit: Normal\r\nFilling material: 100% polyester\r\nModel Length: 78 cm in size M\r\nMaterial Outer: 100% Nylon\r\nArticle ID: ES1-xzw-0178-99', 177, 0),
('Outfitters Nation DARWIN - jacket - black', 'Details Outfitters Nation DARWIN - jacket - black\r\n\r\nThe winter jacket from Darwin Outfitters Nation in Black is a classic quilted down jacket with hood so. The hood can be removed as needed as it is attached with snaps. A padded collar and knit cuffs on the sleeves even on cold days for a warm fuzzy feeling. Two side pockets and looked inside pockets provide ample space for valuable small items. Rounding out the jacket with an embroidered emblem on the left chest. warmed Classic, stylish and well you can enjoy the winter - with the black down jacket from Darwin Outfitters Nation!\r\n\r\ndetachable hood\r\nadjustable waistband\r\ninside pocket\r\nKnitted cuffs\r\nCare instructions: Wash at 30 degrees\r\nLength: Medium\r\nFit: Normal\r\nFilling material: 60% down, 40% feathers\r\nModel Length: 71 cm in size M\r\nSleeve length: 67 cm in size M\r\nMaterial Outer: 100% polyester\r\nModel: OU122D001-802', 112, 0),
('More Views  Scotch & Soda winter jacket - blue', 'Details for Scotch & Soda winter jacket - blue\r\n\r\nThe blue down jacket of Scotch & Soda creates one thing for sure: to keep warm in winter! Thanks to the filling of down and feathers, the jacket is a guarantee of warm days in the cold season. The chic quilted jacket model has adjustable fit cuffs, high collar and two front pockets which are closed by buttons. Sporty design with black shoulders and label patch on the left upper arm. Can not stand a chance in the winter - the Scotch & Soda Down Jacket in blue!\r\n\r\nadjustable sleeve accounts\r\nHem with adjustable elastic\r\nCare instructions: Wash at 30 degrees\r\nLength: Medium\r\nFit: Normal\r\nFilling material: 90% down, 10% feathers\r\nModel Length: 69 cm in size M\r\nSleeve length: 67 cm in size M\r\nMaterial Outer: 100% polyester\r\nModel: SC322D002-952', 147, 0),
('Revolution COLLEGE - Windbreaker - Blue', 'Details for Revolution COLLEGE - Windbreaker - Blue\r\n\r\nThe cool retro design, is the COLLEGE Windbreaker by revolution and brings fresh air to the dreary rain. The yellow accents shine from afar. The body lining is 100% cotton and thus provides a particularly good fit. In the light spot on gray days - wind breaker COLLEGE of revolution in blue.\r\n\r\nHooded\r\nwhite logo on the chest\r\nCare instructions: machine wash at 30 degrees, not suitable dryer\r\nLength: Medium\r\nFit: Normal\r\nFilling material: 97% cotton, 3% spandex\r\nModel Length: 69 cm in size M\r\nSleeve length: 68 cm in size M\r\nMaterial Outer: 100% Nylon\r\nModel: RE6-xzw-0040-99', 132, 0),
('Selected Homme STEVEN - jacket - black', 'Details for Selected Homme STEVEN - jacket - black\r\n\r\nNow the American College classic - the jacket STEVEN by Selected Homme in black! With color-contrasting cuffs and pocket edging and striped cuffs and blouson cut the black jacket College presents very classical. The quilted black lining completes the sporty style perfectly, a highlight is the large patch on the breast and the bright buttons. For true lovers: the black jacket STEVEN College of Selected Homme!\r\n\r\nPatch on the breast\r\nCollege style\r\nZip\r\nstriped cuffs\r\nSleeveless Shell: 100 polyurethane sleeve lining: 100% polyester\r\nCare Instructions: Cleaning\r\nLength: Medium\r\nFit: Normal\r\nFilling material: 100% cotton\r\nModel Length: 65 cm in size M\r\nSleeve length: 63 cm in size M\r\nMaterial Outer: 50% wool, 50% polyester\r\nModel: SE6-xzw-0087-99', 199, 5);

-- --------------------------------------------------------

--
-- Table structure for table `Mens_Jeans`
--

CREATE TABLE IF NOT EXISTS `Mens_Jeans` (
  `item_Name` varchar(255) NOT NULL,
  `item_Description` text NOT NULL,
  `item_Price` double NOT NULL,
  `rating_Value` int(11) NOT NULL,
  PRIMARY KEY (`item_Name`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `Mens_Jeans`
--

INSERT INTO `Mens_Jeans` (`item_Name`, `item_Description`, `item_Price`, `rating_Value`) VALUES
('Nudie Slim Jim - jeans - blue', 'Details for Nudie Slim Jim - jeans - blue\r\n\r\nThe long-standing straight-leg cut is always good: the SLIM JIM Jeans by Nudie jeans in blue shows the way! The classic 5-pocket system and its bronze zipper are almost symbolic of the feel of the jeans. The fabric has a hint of spandex pants and gives an easy-to dehnbahre form. The Washed-out effect completes the picture from complete - that is the blue denim jeans by Nudie Slim Jim is a classic in terms Jeanswear!\r\n\r\nslurred rivets on the pockets\r\nUsed light effects on Taschensaum\r\nPrinted bag inside\r\nCare instructions: Wash at 40 degrees, not suitable for drying\r\nFit: Normal\r\nInseam: 79 cm for size 32\r\nOuter leg length: 105 cm for size 32\r\nBody height: normal\r\nMaterial Outer: 98% cotton, 2% elastane\r\nModel: NU2-yzw-0015-99', 135, 0),
('Nudie Grim Tim - Jeans - frosty blue', 'Details for Nudie Grim Tim - Jeans - frosty blue\r\n\r\nNudie Jeans GRIM TIM of dark blue - the stylish appearance with slim straight leg shape! The fact that the slim fit men also well set the scene shows GRIM TIM: With regular waist height, straight and narrow shape popular five-pocket Deisgn man stands on the right side of fashion. Stylish bright washes around the knee followed by games in wrinkle appearance. The dark blue jeans by Nudie Grim Tim shows: stylish not go!\r\n\r\nlight wash-off set\r\nPartein creased effect\r\nCare instructions: Wash at 40 degrees\r\nFit: Normal\r\nInseam: 80 cm for size 32/32\r\nOuter leg length: 107 cm for size 32/32\r\nBody height: normal\r\nMaterial Outer: 100% cotton\r\nModel: NU2-xzw-0032-99', 112.98, 0),
('Wrangler - Jeans - Twelve Bar', 'Details for Wrangler - Jeans - Twelve Bar\r\n\r\nThe new Wrangler jeans in blue by MILES - in high-quality vintage look! Edel washed out the blue jeans MILES Wrangler comes with minimal leg exhibited in individual 5-pocket style. MILES can be concluded by Button and has translucent creases on the thighs, on the knee and at the boot-cut hem. Distressed deluxe: the blue jeans by Wrangler MILES!\r\n\r\n5-pocket style\r\nButton-Fly\r\nDistressed with wrinkles\r\nCare instructions: machine wash 40 degrees\r\nInseam: 88 cm for size 32/34\r\nOuter leg length: 108 cm for size 32/34\r\nBody height: normal\r\nMaterial Outer: 100% cotton\r\nModel: WR1-xzw-0075-99', 100, 0),
('Diesel Larkee Straight Leg 73n - jeans - dark denim', 'Details for Diesel Larkee Straight Leg 73n - jeans - dark denim used\r\n\r\nThe casual jeans LARKEE of diesel scores with their cool loose-fit! Its solid and robust denim and her 5-pocket style give it a classic touch. The jeans LARKEE looks authentic with its washed-out appearance in dark blue and turns them into another classic of popular labels from Italy. The jeans LARKEE of diesel can be worn both as casual wear as well as going out to cool outfit!\r\n\r\n5-pocket style\r\nButton-Fly\r\nCare instructions: machine wash at 30 degrees, not suitable dryer\r\nFit: wide-\r\nInseam: 94 cm for size 32/36\r\nOuter leg length: 120 cm for size 32/36\r\nBody height: normal\r\nMaterial Outer: 100% cotton\r\nModel: DI1-xzw 0089-99', 132, 0),
('Wrangler - Jeans - blue special', 'Details for Wrangler - Jeans - blue special\r\n\r\nThe new Wrangler Jeans MILES of blue - a cool vintage look! Cool washed with a slight greenish tint comes from the blue jeans MILES Wrangler with straight leg in individual 5-pocket style. MILES can be closed with a zipper and button and has translucent creases on flared leg. Distressed deluxe: the blue jeans by Wrangler MILES!\r\n\r\n5-pocket style\r\nZip and button\r\nDistressed with wrinkles\r\nCare instructions: machine wash 40 degrees\r\nFit: wide-\r\nInseam: 85 cm for size 32/34\r\nOuter leg length: 103 cm for size 32/34\r\nBody height: normal\r\nMaterial Outer: 100% cotton\r\nModel: WR1-xzw-0012-99', 125, 0),
('Energy jeans - blue', 'Details for energy jeans - blue\r\n\r\nJeans in Blue of energy. Style Clash called energy this cool version. The piece has been edited for consuming a powerful vintage feel - change brightened and roughened points away. The section is normal to slightly narrow. A cool part that makes a lot Eighties feeling all right - in blue dieJeans of energy.\r\n\r\ncut normal to slightly narrower\r\nwhitened and roughened surfaces\r\nCare instructions: Wash at 40 degrees\r\nFit: Normal\r\nInseam: 80 cm for size 31/32\r\nOuter leg length: 99 cm for size 31/32\r\nBody height: normal\r\nMaterial Outer: 100% cotton\r\nModel: EN1-xzw 0101-99', 92, 0),
('Lee KNOX - jeans - light stone', 'Details for Lee KNOX - jeans - light stone\r\n\r\nThe blue jeans KNOX Lee in blue - the absolute classic! In the usual 5-pocket style with subtle abrasions, the blue jeans by Lee comes with the straight-cut leg. KNOX can be concluded with a casual button closure and logo button. The comfortable Jeans has subtle stitching on back pockets and a brown leather logo patch. Cool casual look in medium blue wash: the Lee Jeans KNOX!\r\n\r\nRegular Fit\r\n5-pocket style\r\nButton-Fly\r\nCare instructions: Wash at 40 degrees\r\nFit: Normal\r\nInseam: 80 cm for size 32/32\r\nOuter leg length: 105 cm for size 32/32\r\nBody height: normal\r\nMaterial Outer: 100% cotton\r\nModel: LE4-xzw 0063-99', 125, 0),
('Pepe Jeans Straight Leg Scratched V23 - Jeans - indigo', 'Details for Pepe Jeans Straight Leg Scratched V23 - Jeans - indigo\r\n\r\nPepe Jeans stands for quality and style - just like the dark blue jeans with straight leg and easy washing. Five pockets provide ample space for keys and coins. The jeans is made of cotton, providing comfort and durability. A small embroidered logo on the front pocket and a leather patch on the collar back betray the origin of the jeans and dark blue - Tommy Hilfiger!\r\n\r\n5-pocket style\r\nButton-Fly\r\nCare instructions: machine wash 30 degrees\r\nFit: Normal\r\nInseam: 83 cm for size 32/32\r\nOuter leg length: 109 cm for size 32/32\r\nBody height: normal\r\nMaterial Outer: 100% cotton\r\nModel: PE1-xzw-0038-99', 82.99, 0),
('Jack & Jones RICK JJ LEON 449 SUP - Jeans - dark blue', 'Details for Jack & Jones RICK JJ LEON 449 SUP - Jeans - dark blue\r\n\r\nRICK JJ LEON 449 SUP, a pair of jeans made by Jack & Jones, which looks cool and also practical. The LEON RICK JJ boasts 449 SUP jeans in dark blue with their used-look and the two zippered pockets. Just casual, to the elegant blue jeans by Jack & Jones RICK JJ LEON 449 SUP.\r\n\r\nTwo zip pockets\r\nLogo patches\r\nCare instructions: Wash at 40 c\r\nFit: Normal\r\nInseam: 81 cm for size 32/34\r\nMaterial: Cotton\r\nOuter leg length: 104 cm for size 32/34\r\nBody height: normal\r\nMaterial Outer: 100% cotton\r\nModel: JA2-xzw-0304-99', 170, 0),
('Lee FLINT - Jeans - Dark Stone', 'Details for Lee FLINT - Jeans - Dark Stone\r\n\r\nCasual bootcut-style with FLINT, Blue Jeans by Lee! In elegant dark blue wash presents itself permeable leg jeans by Lee with the trendy button closure. FLINT is far away and comes in a classic 5-pocket style with ocher-colored and on the back pockets wavy stitching. Cool casual look that can be combined easily with everything: the blue jeans by Lee FLINT!\r\n\r\n5-pocket style\r\nButton fly and logo button\r\nCare instructions: machine wash 40 degrees\r\nFit: wide-\r\nInseam: 81 cm for size 32/32\r\nOuter leg length: 102 cm for size 32/32\r\nBody height: normal\r\nMaterial Outer: 100% cotton\r\nModel: LE4-xzw 0103-99', 132, 0);

-- --------------------------------------------------------

--
-- Table structure for table `Mens_Pants`
--

CREATE TABLE IF NOT EXISTS `Mens_Pants` (
  `item_Name` varchar(255) NOT NULL,
  `item_Description` text NOT NULL,
  `item_Price` double NOT NULL,
  `rating_Value` int(11) NOT NULL,
  PRIMARY KEY (`item_Name`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `Mens_Pants`
--

INSERT INTO `Mens_Pants` (`item_Name`, `item_Description`, `item_Price`, `rating_Value`) VALUES
('Solid PAVEL - pants - gray', 'Details for Solid PAVEL - pants - gray\r\n\r\nPAVEL: Very elegant and soft pants made of Solid Collection in gray! With these pants, you are smart and casual styled - for any occasion. The 5-pocket style with Paspeleingriffen offers enough space for small belongings. The pants PANTS-PAVEL from the Solid Collection is an absolute gem with high wearing comfort. Smart and casual - with the new trousers in gray PAVEL Solid!\r\n\r\nHidden zipper\r\n5-pocket style\r\nCare instructions: machine wash at 30 degrees, not suitable dryer\r\nFit: Normal\r\nInseam: 82 cm for size 32/32\r\nOuter leg length: 105 cm for size 32/32\r\nBody height: normal\r\nMaterial Outer: 100% cotton\r\nModel: SO422B00D-102', 100, 0),
('Tommy Hilfiger MERCER - Chino - blue', 'Details for Tommy Hilfiger MERCER - Chino - blue\r\n\r\nDandy in the fashionable style, the MERCER Chino Pants presented by Tommy Hilfiger in the color dark blue! Her soft material made of pure cotton provides a comfortable fit. The pants are equipped with zipper, side pockets and two back pockets with buttons. Through her timeless style to fit both into the office as well as for leisure outfit. In the dark blue MERCER Chino Pants by Tommy Hilfiger makes man guaranteed a good figure!\r\n\r\nside slit pockets and two back pockets with buttons\r\nBelt loops\r\nFit: Normal\r\nInseam: 78 inches in size W32 L32\r\nOuter leg length: 104 cm in size W32 L32\r\nBody height: normal\r\nMaterial Outer: 100% cotton\r\nModel: TO1-xzw-0096-99', 152, 0),
('ESPRIT Collection Pants - Pants', 'Details for ESPRIT Collection Pants - Pants -\r\n\r\nPure understatement! The new trousers in gray Esprit Collection comes in a classic and elegant, with. The belt loops and branded decorative buttons emphasize the casual style of the pants. The 5-pocket system gives the trousers in gray the classic touch. The gray pants in the house of Esprit Collection - convinced an all-rounder!\r\n\r\nhidden placket\r\nand wash and iron from the left\r\nLining: 100% cotton\r\nCare instructions: machine wash at 30 degrees, not suitable dryer\r\nFit: Normal\r\nInseam: 84 cm for size 32/34\r\nOuter leg length: 109 cm for size 32/34\r\nBody height: normal\r\nMaterial Outer: 70% cotton, 30% Lyocell\r\nModel: ES4-xzw 0099-99', 125, 0),
('Calvin Klein Jeans Chino - blue', 'Details for Calvin Klein Jeans Chino - blue\r\n\r\nChino in Blue by Calvin Klein. Calvin Klein classic is quite the thing here. The Chino cotton meets a laid-back section and a chic blue-tone. With this listing can nothing go wrong. For office or recreation - this Chino, we are always well dressed. Chino in Blue by Calvin Klein.\r\n\r\nRelaxed fit\r\nCare instructions: Wash at 30 degrees\r\nFit: Normal\r\nInseam: 85 inches in size L34\r\nOuter leg length: 110 cm in size L34\r\nBody height: normal\r\nMaterial Outer: 100% cotton\r\nModel: C18-xzw 0048-99', 162, 0),
('Esprit GROOVE L32 - Pants - beige timber', 'Details for Esprit GROOVE L32 - Pants - beige timber\r\n\r\nGROOVE - the new corduroys made by Esprit Beige is a real feel-good pants! The beige-colored, soft but sturdy Cord fabric made pants are very comfortable against the skin. Closed the pants will fit with a hidden zip-fly and the subtle seams and decorative stitching of corduroys GROOVE is well into the overall picture of the beige corduroy GROOVE one of the brand Esprit!\r\n\r\nZip-Fly\r\n2 side pockets\r\n2 hip pockets\r\nCare instructions: machine wash 40 degrees\r\nFit: Normal\r\nInseam: 79 cm\r\nOuter leg length: 104 cm\r\nBody height: normal\r\nMaterial Outer: 100% cotton\r\nArticle ID: ES1-xzw-0180-99', 135, 0),
('Hilfiger Denim SASHA - trousers - plaza taupe', 'Details for Tommy Hilfiger SASHA - trousers - plaza taupe\r\n\r\nA true classic: the beige trousers SASHA by Hilfiger Denim. These pants come in without any pomp. The soft material made of pure cotton beige SASHA ensures a comfortable fit, while a discreet Tommy Hilfiger brand logo knowingly on the back pocket of the origin of this jewel suggesting. A pretty basic and a must in every wardrobe: the beige trousers SASHA by Hilfiger Denim.\r\n\r\nStraight Cut\r\nBack pocket with brand logo\r\nCare instructions: Wash at 40 degrees\r\nFit: Normal\r\nInseam: 78 cm for size 32/32\r\nOuter leg length: 102 cm for size 32/32\r\nBody height: normal\r\nMaterial Outer: 100% cotton\r\nItem number: HI1-xzw-0023-99', 190, 0),
('ESPRIT Collection trousers (track 34) - gray', 'Details for ESPRIT Collection trousers (track 34) - gray\r\n\r\nSimple and comfortable - the gray trousers of Esprit. The fine checked pattern and light cotton fabric make for a high level of comfort. The 5 pocket design and gray stitching miss out on the back pockets of these pants a decent, not too flashy look. Comes with straight legs - the new trousers in gray Esprit\r\n\r\n5 Pocket\r\nStraight Leg\r\nCare instructions: machine wash at 40 degrees, not suitable dryer\r\nFit: Normal\r\nInseam: 84 cm for size 31/34\r\nOuter leg length: 112 cm for size 31/34\r\nBody height: normal\r\nMaterial Outer: 100% cotton\r\nModel: ES4-xzw 0053-99', 197, 0),
('Levi''s Chino - Black', 'Details for Levi''s Chino - Black\r\n\r\nChic - the new black Chino from Levi''s! Impressively here are the simple look and the beautiful details. While the front pockets were admitted here are inclined to recognize only the rear of the slots. Button fly, straight leg and a wide waistband ensure comfort. Also nice to see is the blue and white striped lining of the pants. With a lot of potential to favorite pants - the black Levi''s Chino!\r\n\r\nobliquely inset front pockets\r\nStraight legs\r\nCare instructions: Wash at 40 degrees\r\nFit: Normal\r\nInseam: 87 cm for size 32/34\r\nOuter leg length: 115 cm for size 32/34\r\nBody height: normal\r\nMaterial Outer: 100% cotton\r\nModel: LE 2-xzw-0063-99', 192, 0),
('ESPRIT Collection Hose - earthy brown', 'Details for ESPRIT Collection Hose - earthy brown\r\n\r\nVery elegant and soft pants from Esprit Collection in brown! With these pants, you are smart casual styling - for any occasion. At the back is a leather label with logo branding and right front pocket is an additional penny. The pants from Esprit Collection is narrowing slightly to the hem. Smart and casual - with the new trousers with herringbone pattern of ESPRIT Collection in brown!\r\n\r\nHerringbone pattern\r\nPenny Pocket\r\nCare instructions: Wash at 30 c, not suitable dryer\r\nFit: Normal\r\nInseam: 83 cm for size 50\r\nOuter leg length: 105 cm for size 50\r\nBody height: normal\r\nMaterial Outer: 98% cotton, 2% spandex\r\nModel: ES4-xzw 0101-99', 187.6, 0),
('DKNY pants - black', 'Details for DKNY pants - black\r\n\r\nSchick - the black cloth pants by DKNY. These pants come in a clear design, therefore, with five pockets. Section of materials and offer much comfort in wear at any time. Whether at work or in everyday life, with the black cloth pants by DKNY make a good figure.\r\n\r\n5 pockets\r\nCare instructions: Wash at 40 degrees\r\nFit: Normal\r\nInseam: 86 cm for size 32\r\nOuter leg length: 111 cm for size 32\r\nBody height: normal\r\nMaterial Outer: 100% cotton\r\nModel: DK1-xzw-0065-99', 142, 0),
('Esprit GROOVE FIT - Cargo pants - dark burnt metal', 'Details for Esprit GROOVE FIT - Cargo pants - dark burnt metal\r\n\r\nCargo pants in dark gray GROOVE FIT Esprit - modern design! The trousers with straight legs and low waist height is made of thick solid tissue in Washed look. The typical large pockets in front, here set at a slight angle will not be missing in this model. Among them is a Penny Pocket and right join used flap pockets on the sides and bottom. Inside, the gray cargo pants GROOVE FIT Esprit blue floral displays documents in federal and bags. The waistband with belt loops, retro flag label and buttoned fly completes the design of the gray Esprit GROOVE FIT pants in gray!\r\n\r\nWashed-look\r\nlarge right front pockets plus Penny Pocket\r\nCare instructions: Wash at 40 degrees\r\nFit: Normal\r\nInseam: 84 cm for size 32/34\r\nOuter leg length: 109 cm for size 32/34\r\nWaist: low\r\nMaterial Outer: 100% cotton\r\nArticle ID: ES1-xzw-0074-99', 135, 0),
('Campus by Marc O''Polo NELSON - Chino - clay', 'Details for Campus by Marc O''Polo NELSON - Chino - clay\r\n\r\nSend chino NELSON from the Campus by Marc O''Polo quality home. This comes with two button-through slit pockets Chino, two side pockets and hidden button placket. Particularly, the elegant, yet casual pinstripe look. Comfortable cotton material and casual cut, it is suitable for many Gelegehnheiten Chino - NELSON simply by Campus by Marc O''Polo in blue.\r\n\r\nhidden button\r\nPinstripe-look\r\nCare instructions: Wash at 30 degrees\r\nFit: Normal\r\nInseam: 82 cm for size 32\r\nOuter leg length: 105 cm for size 32\r\nBody height: normal\r\nMaterial Outer: 100% cotton\r\nModel: CA9-xzw-0026-99', 172, 0);

-- --------------------------------------------------------

--
-- Table structure for table `Mens_Shirts`
--

CREATE TABLE IF NOT EXISTS `Mens_Shirts` (
  `item_Name` varchar(255) NOT NULL,
  `item_Description` text NOT NULL,
  `item_Price` double NOT NULL,
  `rating_Value` int(11) NOT NULL,
  PRIMARY KEY (`item_Name`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `Mens_Shirts`
--

INSERT INTO `Mens_Shirts` (`item_Name`, `item_Description`, `item_Price`, `rating_Value`) VALUES
('Jack & Jones', 'Details for Jack & Jones ARROW - Longsleeve - pacific blue\r\n\r\nTrendy design + gaudy colors = ARROW Shirt Jack & Jones. The soft cotton material is comfortable against the skin and in addition, is also provided with a casual print. The new Arrow Shirt Jack & Jones - simply irresistible!\r\n\r\ncasual Print\r\nBright colors\r\nCare instructions: machine wash at 40 degrees, not suitable dryer\r\nFit: Narrow\r\nModel length: 67cm in size M\r\nMaterial Outer: 100% cotton\r\nModel: JA2-xzw-0397-99', 195, 0),
('Ellesse POLO LONG', 'The polo shirt POLO LONG of Ellesse in white! This sporty polo shirt in the innovative Italian style. Two large logo patches sewn on the left and right on the chest and the blue collar has a particularly transparent to the red sleeves. Through the day with the sporty polo shirt POLO LONG of Ellesse in white!\r\n\r\n2 buttons\r\nelastic material\r\nLogo patches\r\nCare instructions: machine wash 30 degrees\r\nFit: Normal\r\nModel Length: 68 cm in size M\r\nMaterial Outer: 100% cotton\r\nModel: EL922F003-002', 84.95, 0),
('Iight gray melange', 'Trendy design + translucent colors = ARROW Shirt Jack & Jones. The soft cotton material is comfortable against the skin and in addition, is also provided with a casual print. The new Arrow Shirt Jack & Jones - simply irresistible!\r\n\r\nPrint in vintage style\r\nCare instructions: machine wash at 40 degrees, not suitable dryer\r\nFit: Narrow\r\nModel length: 68cm in size M\r\nMaterial Outer: 100% cotton\r\nModel: JA2-xzw-0395-99', 17, 0),
('Longsleeve - optical white', 'Details for Jack & Jones ARROW - shirt - optical white\r\n\r\nTrendy design + gaudy colors = ARROW Shirt Jack & Jones. The soft cotton material is comfortable against the skin and in addition, is also provided with a casual print. The new Arrow Shirt Jack & Jones - simply irresistible!\r\n\r\nPrint in vintage style\r\nCare instructions: machine wash at 40 degrees, not suitable dryer\r\nFit: Narrow\r\nModel length: 68cm in size M\r\nMaterial Outer: 100% cotton\r\nModel: JA2-xzw-0396-99', 26.95, 0),
('T-Shirt - anchor blue', 'Details for Jack & Jones WINNER - T-Shirt - Anchor Blue\r\n\r\nBe a WINNER - with the purple T-shirt from Jack & Jones! Made from purple cotton fabric, the shirt is especially comfortable against the skin. The round neckline completes the classic look from skilfully. The large print on the front shows the origin of the T-shirts - Jack & Jones WINNER in purple!\r\n\r\nCrew neck\r\nPrint on front\r\nCare instructions: 40 degrees machine wash, not suitable dryer\r\nFit: Normal\r\nModel Length: 69 cm in size M\r\nMaterial Outer: 100% cotton\r\nModel: JA222F00S-502', 12, 0),
('Hilfiger Denim FEDERER', 'Details for Tommy Hilfiger FEDERER - T-Shirt - Green\r\n\r\nSporty goes Style - with the green T-Shirt FEDERER made by Tommy Hilfiger! The T-Shirt FEDERER of Tommy Hilfiger in green comes in a straight cut and relaxed collar. The front print in orange and white gives the T-shirt sporting the certain something. Cool with jeans or shorts on the beach - The T-Shirt FEDERER by Hilfiger Denim by Tommy Hilfiger in green!\r\n\r\nPrinted Label\r\nRound Neck\r\nCare instructions: Wash at 40 degrees\r\nFit: Normal\r\nModel Length: 70 cm in size M\r\nMaterial Outer: 100% cotton\r\nItem number: HI1-xzw-0029-99', 29, 0),
('CROSS EDGE optical white', 'Details for Jack & Jones CROSS EDGE - T-shirt - optical white\r\n\r\nCROSS EDGE - stylish T-shirt from the collection of Jack & Jones! Made of white cotton cloth, the shirt is especially comfortable against the skin. The large logo printed on the chest shows the origin of the casual T-shirts - Jack & Jones CROSS EDGE in white!\r\n\r\nCrew neck\r\nLogo printed on the chest\r\nCare instructions: machine wash at 40 degrees, not suitable dryer\r\nFit: Normal\r\nModel Length: 65 cm in size M\r\nMaterial Outer: 100% cotton\r\nModel: JA222F00O-002', 17.6, 0),
('CROSS EDGE optical  black', 'Details for Jack & Jones CROSS EDGE - T-shirt - black\r\n\r\nCROSS EDGE - stylish T-shirt from the collection of Jack & Jones! Made of black cotton fabric, the shirt is especially comfortable against the skin. The large logo printed on the chest shows the origin of the casual T-shirts - Jack & Jones CROSS EDGE in black!\r\n\r\nCrew neck\r\nLogo printed on the chest\r\nCare instructions: 40 degrees machine wash, not suitable dryer\r\nFit: Normal\r\nModel Length: 65 cm in size M\r\nMaterial Outer: 100% acetate\r\nModel: JA222F00O-802', 12.98, 0),
('Longsleeve - Grey melange', 'Details for Selected Homme ANOUK DOUBLE - Longsleeve - Grey melange\r\n\r\nANOUK DOUBLE - boring in any way, the gray sweater by Selected Homme! This sweater is presented as more appropriate Basic. The classic V-neck with the button bar and great layered look to make a good impression. The lightweight cotton feels good on the skin and is perfect with jeans but also to the business style. ANOUK DOUBLE in gray of Selected Homme - fits all!\r\n\r\nLayering\r\nV-neck\r\nCare instructions: Wash at 40 degrees\r\nFit: Normal\r\nModel Length: 64 cm in size M\r\nMaterial Outer: 100% cotton\r\nModel: SE622F004-111', 17.6, 0),
('edc by Esprit T-shirt - white', 'Details for edc by Esprit T-shirt - white\r\n\r\nClassic shirt for every day! The white T-shirt from Esprit comes on the classic shirt cut. A real highlight is the blue-print in red brush stroke look at breast height. A beautiful and stylish part that always fits: the white T-shirt from Esprit!\r\n\r\nBrush strokes-Print\r\nNext round neck\r\nCare instructions: machine wash at 40 degrees, not suitable dryer\r\nFit: Normal\r\nModel Length: 66 cm in size M\r\nMaterial Outer: 100% cotton\r\nItem Number: ED1-xzw-0231-99', 39, 0),
('Camel Active Longsleeve - red', 'Details for Camel Active Shirt - red\r\n\r\nThe wine red longsleeve from Camel Active - even on cold days look cool! The Shirt is made of thick and soft cotton. The button bar is hidden and cuffs on the sleeves are attached. The two slots on the sides make Longsleeve pleasantly casual. The wine red longsleeve from Camel Active - just well dressed!\r\n\r\nthick fabric\r\nhidden placket\r\nCuffs\r\nCare instructions: machine wash at 30 degrees, not suitable dryer\r\nFit: Normal\r\nModel Length: 74 cm in size M\r\nMaterial Outer: 100% cotton\r\nModel: CA5-xzw-0076-99', 40, 0),
('Camel Active Longsleeve - blau', 'Details for Camel Active Shirt - Blue\r\n\r\nSend a strip comes with the blue shirt from Camel Active! The Polo Shirt has a collar and placket with three buttons. His elastic cuffs provide a comfortable fit. The soft material is made of pure cotton. Basic Chic-Shirt: Shirt of the Camel Active in blue!\r\n\r\nPolo collar\r\nPlacket with 3 buttons\r\nelastic cuffs\r\nCare instructions: machine wash at 30 degrees, not suitable dryer\r\nFit: Normal\r\nModel Length: 71 cm in size L\r\nMaterial Outer: 100% cotton\r\nModel: CA5-xzw-0032-99', 26.95, 0);

-- --------------------------------------------------------

--
-- Table structure for table `Womens_Cardigans`
--

CREATE TABLE IF NOT EXISTS `Womens_Cardigans` (
  `item_Name` varchar(255) NOT NULL,
  `item_Description` text NOT NULL,
  `item_Price` double NOT NULL,
  `rating_Value` int(11) NOT NULL,
  PRIMARY KEY (`item_Name`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `Womens_Cardigans`
--

INSERT INTO `Womens_Cardigans` (`item_Name`, `item_Description`, `item_Price`, `rating_Value`) VALUES
('Object Siguler TRUE - Cardigan - Black & White', 'Details for Object Siguler TRUE - Cardigan - Black / White\r\n\r\nThe cardigan Siguler TRUE Object in black and white. Beautiful knitwear from the finest wool material with cuddly angora share. High level of comfort with tie belt and a large hood! The winter is coming! With the stylish cardigan Siguler TRUE Object in black and white!\r\n\r\nKnitted cuffs and hem\r\nHooded\r\ntwo front pockets\r\nCare instructions: machine wash at 30 degree, not suitable dryer\r\nLength: Medium\r\nFit: Normal\r\nModel Length: 80 cm in size S\r\nSleeve length: 75 cm in size S\r\nMaterial Outer: 35% wool, 30% Nylon, 27% viscose, 8% Angora\r\nModel: OB1-yzw 0041-99', 270, 0),
('Tommy Hilfiger CARDIGAN COLE - cardigan - new twilight blue', 'Details for Tommy Hilfiger CARDIGAN COLE - cardigan - new twilight blue\r\n\r\nCashmere Blend: blue Tommy Hilfiger sweater CARDIGAN COLE. Besides the refreshing color COLE CARDIGAN impresses with its pleasant feeling on the skin. Kashmir pampers the delicate skin of women and provides a special feel-good factor. High quality knitwear from Tommy Hilfiger: COLE CARDIGAN in bright blue.\r\n\r\nDeep V-neck\r\nCare instructions: Hand wash\r\nFit: Normal\r\nModel Length: 83 cm in size S\r\nMaterial Outer: 66% cotton, 20% Nylon, 11% cashmere, 3% elastane\r\nModel: TO1-yzw-0212-99', 290, 0),
('Maison Scotch cardigan - white & blue', 'Details for Maison Scotch cardigan - white / blue\r\n\r\nAhoy sailor! The blue and white striped sweater from Maison Scotch presents itself in the popular nautical look. Blue and white stripes and gold buttons controls with a nice embossed anchor the look and make the pretty Scotch Maison cardigan a must-have! Whether with jeans or a dress in blue and white sweater is the icing on the cake for any outfit. The blue and white striped sweater from Maison Scotch you never want to give back!\r\n\r\nAnchor embossed on the buttons\r\ninset pockets\r\nLength: Medium\r\nFit: Normal\r\nModel Length: 62 cm in size S\r\nSleeve length: 59 cm in size S\r\nMaterial Outer: 39% viscose, 32% Nylon, 21% cotton, 8% Angora\r\nItem number: MA4-yzw-0087-99', 260, 0),
('Lacoste Bairols - Cardigan - eclipse & garance', 'Details for Lacoste Bairols - Cardigan - eclipse / garance\r\n\r\nEdler retro look - the cardigan Bairols in blue and red from Lacoste! This cardigan comes in a fine merino wool, therefore, the special luxury and softness when worn on the skin provides direct. Moreover Bairols is held in a chic retro look that can revive the glory days gone by. The length of the sleeves of the sweater sets just released the wrist, which gives the jacket a very feminine touch. The blue and red cardigan Bairols Lacoste - Retro has never been more beautiful!\r\n\r\nMerino\r\nRetro Look\r\nCare instructions: Hand wash\r\nFit: Normal\r\nModel Length: 58 cm in size M\r\nMaterial Outer: 100% wool\r\nArticle ID: LA2-yzw-0027-99', 170, 0),
('Polo Jeans MELISSA - cardigan - antique cream', 'Details for Polo Jeans MELISSA - cardigan - antique cream\r\n\r\nThe cream-white sweater by Polo Jeans MELISSA nestles comfortably soft to the body and is the perfect garment for cold days. The loose-fitting design with two patch Tasca radiates serenity. The new sweater in cream white MELISSA Polo Jeans will enchant you and embellish cold days!\r\n\r\npockets\r\nCare instructions: machine wash 30 degree, not suitable dryer\r\nFit: wide-\r\nModel Length: 67 cm in size S\r\nMaterial Outer: 100% cotton\r\nModel: PO4-yzw 0061-99', 255.99, 0),
('Vila Mysig - Cardigan - iron gray', 'Details Vila Mysig - Cardigan - iron gray\r\n\r\nHeated in the winter - the brown sweater Mysig of Vila. Black, brown and patterned jacket winter presents itself. Made from a soft and warm material mix, it will be completed with a black hood and knit cuffs. Mysig the brown cardigan Vila.\r\n\r\nhooded\r\nCare Instructions: Cold wash, not suitable dryer\r\nLength: Medium\r\nFit: Normal\r\nModel Length: 57 cm in size\r\nSleeve length: 61 cm in size S\r\nMaterial Outer: 90% acrylic, 5% nylon, 5% Angora\r\nModel: V1021A00M-802', 299.99, 0),
('DEPT cardigan - night shadow', 'Details DEPT cardigan - night shadow\r\n\r\nPure comfort - the blue cardigan Dept. A wide lapels, wide half sleeves and a belt make this comfortable sweater unique. Wonderful blue and gray knit complement and define the look. The blue cardigan Dept. - the true comfort.\r\n\r\nWide lapel\r\nwith belt\r\nCare instructions: Hand wash, not suitable dryer\r\nFit: Normal\r\nModel Length: 75 cm in size S\r\nMaterial Outer: 70% acrylic, 30% wool\r\nModel: DE5-yzw-0084-99', 235, 0),
('Vila Mysig - Cardigan - crema & Corsar blu', 'Details Vila Mysig - Cardigan - crema / Corsar blu\r\n\r\nHeated in the winter - the blue cardigan Mysig of Vila. White, blue and patterned jacket winter presents itself. Made from a soft and warm material mix, it will be completed with a white hood and knit cuffs. Mysig, the blue sweater of Vila.\r\n\r\nhooded\r\nCare Instructions: Cold wash, not suitable dryer\r\nModel Length: 57 cm in size\r\nSleeve length: 61 cm in size S\r\nMaterial Outer: 90% acrylic, 5% nylon, 5% Angora\r\nModel: V1021A00M-003', 245.5, 0);

-- --------------------------------------------------------

--
-- Table structure for table `Womens_Category`
--

CREATE TABLE IF NOT EXISTS `Womens_Category` (
  `item_Name` varchar(255) NOT NULL,
  `Field_Name` varchar(255) NOT NULL,
  PRIMARY KEY (`Field_Name`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `Womens_Category`
--

INSERT INTO `Womens_Category` (`item_Name`, `Field_Name`) VALUES
('Vila FLIKA TOP', 'Shirts & Tops'),
('Adidas LOGO ZIP HOODIE', 'Jackets'),
('Wrangler SARA', 'Jeans'),
('Vila Mysig', 'Cardigans'),
('Vero Moda Babeth', 'Dresses');

-- --------------------------------------------------------

--
-- Table structure for table `Womens_Dresses`
--

CREATE TABLE IF NOT EXISTS `Womens_Dresses` (
  `item_Name` varchar(255) NOT NULL,
  `item_Description` text NOT NULL,
  `item_Price` double NOT NULL,
  `rating_Value` int(11) NOT NULL,
  PRIMARY KEY (`item_Name`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `Womens_Dresses`
--

INSERT INTO `Womens_Dresses` (`item_Name`, `item_Description`, `item_Price`, `rating_Value`) VALUES
('Vila Joycee - Dress - smokey gray', 'Details Vila Joycee - Dress - smokey gray\r\n\r\nRomantic: the gray shirt dress Joycee Vila! The elastic material is particularly pleasant to wear and with its numerous rubber bands on the sleeves, neckline and under bust a perfect fit. The chest is ably replaced by the pattern and the ribbons staged. The floral pattern in purple, blue, white and pink looks wonderful from female. For a feminine presence: the gray dress Joycee Vila!\r\n\r\ncomfortable elastic\r\nCare instructions: Wash at 40 degree\r\nLength: Medium\r\nModel Length: 87 cm in size S\r\nMaterial Outer: 100% viscose\r\nModel: V1021I001-102', 237, 0),
('LTB nesli - dress - purple', 'Details for LTB nesli - dress - purple\r\n\r\nFloral paradise! The purple dress nesli of LTB is printed with flowers and reminiscent of a playful garden. The narrow waist belt fits perfectly color and also emphasizes the hip skillfully. A light gathering emphasized the upper body and emphasizes the silhouette. Nesli of LTB in purple is a dress that would not take off man!\r\n\r\nlong sleeves\r\nintegrated belt\r\nModel length: 80cm in size S\r\nMaterial Outer: 60% cotton, 40% polyester\r\nModel: LT1-yzw 0024-99', 199, 0),
('Vila KATT NEW DRESS - Dress - gray sparrow', 'Details for KATT Vila NEW DRESS - Dress - gray sparrow\r\n\r\nWith all its glory, the presents made of satin DRESS NEW KATT Vila in brown. The striking decorative bow at the front gives the dress elegance and charm. Rounding out this look with pleated sleeves. A hidden in the side seam zipper eases the entry and exit. For a female with style is a must - the KATT NEW DRESS in brown by the fashion brand Vila.\r\n\r\nLining 100% polyester\r\nDecorative bow at the front\r\nSide seam zipper\r\nCare instructions: Gentle machine wash 30 degree\r\nLength: Short\r\nModel Length: 84 cm in size S\r\nMaterial Outer: 95% polyester, 5% spandex\r\nModel: V1021I01D-102', 289, 0),
('Coffee Metty - dress - black deep', 'Details for coffee Metty - dress - black deep\r\n\r\nThe black pinafore dress Metty convinced of coffee with his semi-transparent robe, through the shimmering blue under-dress made of soft, flowing fabric falling through. The hem of the dress is decorated with intricate floral embroideries that are repeated on the breast area, and thus draw the eye could. A side zipper for easy on and off. For a romantic look: a black tank dress Metty of coffee!\r\n\r\nsemi-transparent robe\r\nSlip of 100% viscose\r\nCare instructions: Hand wash\r\nLength: Medium\r\nModel Length: 75 cm in size S\r\nMaterial Outer: 100% polyester\r\nModel: KA3-yzw-0123-99', 220, 0),
('Only LONDON WOVEN DRESS - Dress - Caviar & rose of sh', 'Details for Only LONDON WOVEN DRESS - Dress - Caviar / rose of sh\r\n\r\nLONDON WOVEN DRESS from Only - the playful and yet so chic look! Despite the flower pattern summer dress is also quite ladylike. The Etuischnitt is great to be Fitted and slightly flared pleated skirt and round neckline the dress to be a great mix of lightness and elegance. LONDON WOVEN DRESS in Black by Only!\r\n\r\nZipper back\r\nPleated skirt\r\nFitted\r\nCare instructions: machine wash at 40 degree, not suitable dryer\r\nLength: Medium\r\nModel length: 79cm in size S\r\nMaterial Outer: 100% cotton\r\nModel: ON321I001-802', 240, 0),
('Laundry Room DOTS - Dress - Blue', 'Details for Laundry Room DOTS - Dress - Blue\r\n\r\nBack in the 50s! With this dress from Laundry Room DOTS catch you with security, some envious glances. The slight puffed sleeves and elastic at the fitted waist create a great shape and embellished button placket draws the eye to your legs. A beautiful dress can be worn casual or chic, the blue dress by DOTS Laundry Room!\r\n\r\nnarrow waist\r\nslightly puffed sleeves\r\nLace\r\nBags\r\nCare instructions: Hand wash\r\nLength: Medium\r\nModel Length: 90 cm in size S\r\nMaterial Outer: 100% cotton\r\nModel: LA321I00B-503', 260, 0),
('DEPT FLOW DYNASTY - Dress - pistachio', 'Details DEPT FLOW DYNASTY - Dress - pistachio\r\n\r\nColorful elegance is convincing - the colorful dress of FLOW DYNASTY Dept. This light and airy dress with Lagne poor is a real eye catcher. Highlight here is the complex pattern of a floral pattern and a pure stripe design. There are also a slight waist, which is supported by the sewed and wide belt. Great color combinations and beautiful patterns make the design complete. Simply beautiful - the dress of Dept. FLOW DYNASTY!\r\n\r\nwide belt\r\ntight arms\r\nWaterfall collar\r\nCare instructions: Wash at 30 degree\r\nLength: Medium\r\nModel Length: 93 cm in size S\r\nMaterial Outer: 70% polyester, 25% cotton, 5% spandex\r\nModel: DE5-yzw-0103-99', 290, 0),
('Lavand Dress - Brown', 'Details for Lavand Dress - Brown\r\n\r\nBeautifully patterned: the knitted dress from the House Lavand. Even if the color code brown is officially the patterned dress is more likely in gray and white, therefore. Strong material, the short-sleeved dress is perfect for chilly days. The fitted cut is complemented by an issued lower and flatter then the figure. Black shiny buttons are a real eye-catcher at the waist. A beautiful dress for any occasion: Lavande knit dress in gray and white.\r\n\r\nFitted cut\r\nApplications button\r\nCare instructions: Wash at 30 degree\r\nLength: Short\r\nModel Length: 84 cm in size S\r\nMaterial Outer: 90% acrylic, 10% Nylon\r\nArticle ID: LA5-yzw 0003-99', 340, 0),
('Lavand dress - blue', 'Details for Lavand dress - blue\r\n\r\nBeautiful knit dress in blue from Lavand! The wool-like material is contrasted beautifully with the finely woven fabric panels in black on the arms and waist, the skillfully placed in this scene. On the arms and chest the dress is very spacious and offers a comfortable fit. The blue pattern on black background is white and yellow elements adds style, so that a successful overall picture. This is how the winter fun: the blue dress Lavand!\r\n\r\nmore V-neck front and back\r\nCare instructions: Wash at 30 degree\r\nLength: Medium\r\nModel Length: 85 cm in size S\r\nMaterial Outer: 90% acrylic, 10% Nylon\r\nArticle ID: LA5-yzw 0025-99', 289, 0),
('Object X MARY LS DRESS - Dress - verdent army', 'Details for Object X MARY LS DRESS - Dress - verdent army\r\n\r\nBeautiful and comfortable - this is the LS DRESS MARY X is guaranteed in olive green from Object. Draping in the trendy look range, this dress with waterfall ruffles on the sleeves and neckline and skirt. The viscose-elastane mix promises comfort and a perfect fit. Good start in the winter with the X MARY LS DRESS in olive green from Object.\r\n\r\nRuffles on the sleeves and skirt\r\nWaterfall detail\r\nCare instructions: Wash at 30 degree\r\nLength: Short\r\nModel Length: 86 cm in size L\r\nMaterial Outer: 92% viscose, 8% spandex\r\nModel: OB121I00M-604', 340, 0),
('Vila ALLURE - Dress - major blue', 'Details Vila ALLURE - Dress - major blue\r\n\r\nALLURE is the name of the new dark blue dress from the collection of Vila! The body hugging dress presents simple, yet elegant. The embroidered with silver beads on the front part is a real eye catcher and gives the garment its distinctive look! The long sleeves make the dress also the ultimate wardrobe itself on cooler evenings. For women with style - the dark blue dress from Vila ALLURE!\r\n\r\nsilver-colored beads at the top of\r\nCrew neck\r\nCare instructions: Hand wash, not suitable dryer\r\nLength: Medium\r\nModel Length: 89 cm in size S\r\nMaterial Outer: 95% viscose, 5% spandex\r\nModel: V1021I01A-503', 299, 0),
('Uttam London GABY - Dress - Grey', 'Details for Uttam London GABY - Dress - Grey\r\n\r\nGABY by Uttam London - the elegant and sophisticated look! The gray dress is decorated with beautiful applications in champagne and black. The ruffles give the dress an elegant form. GABY, the stylish dress in gray from Uttam London!\r\n\r\nIndoor Rock: 100% cotton\r\nside zipper\r\nCare instructions: Hand wash\r\nModel length: 84cm in size S\r\nMaterial Outer: 100% viscose\r\nModel: UT1-yzw-0023-99', 270, 0);

-- --------------------------------------------------------

--
-- Table structure for table `Womens_Jackets`
--

CREATE TABLE IF NOT EXISTS `Womens_Jackets` (
  `item_Name` varchar(255) NOT NULL,
  `item_Description` text NOT NULL,
  `item_Price` double NOT NULL,
  `rating_Value` int(11) NOT NULL,
  PRIMARY KEY (`item_Name`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `Womens_Jackets`
--

INSERT INTO `Womens_Jackets` (`item_Name`, `item_Description`, `item_Price`, `rating_Value`) VALUES
('Desigual SODA SWEAT - Sweat Jacket - Gray', 'Details for Desigual SODA SWEAT - Sweat Jacket - Gray\r\n\r\nPlayful and attention to detail: the gray sweat jacket SWEAT SODA Desigual! Armed with a colorful all-over print presents itself long and narrow cut Sweat Jacket Desigual of gray flecked cotton. The high collar is made of fine ribbed hem of the sweatshirt and the ends cut off casually. The balloon sleeves of the SWEAT SODA fit perfectly thanks to rubber cuff and miss the gray sweat jacket its own special style. For real trendsetters: the gray sweat jacket SWEAT SODA Desigual!\r\n\r\nhigh collar\r\nBalloon sleeves with elastic\r\nplayful, all-over print\r\nCare instructions: machine wash at 30 degree, not suitable dryer\r\nFit: Narrow\r\nModel Length: 61 cm in size S\r\nMaterial Outer: 100% cotton\r\nModel: DE121C001-102', 100, 0),
('DEPT cardigan - night shadow', 'Details DEPT cardigan - night shadow\r\n\r\nSuper Stylish Cardigan of this Dept. in color is gray! Its soft fabric with viscose component gives a comfortable fit. The extra-wide collar and elastic knit cuffs invite you to cuddle. The different patterned fabric create a great look. Beautiful cardigan in gray Dept. of!\r\n\r\nextra wide collar\r\nElastic knit cuffs\r\nTie belt\r\nKnitting material inserts: 100% acrylic\r\nCare instructions: Wash at 30 degree, not suitable dryer\r\nFit: Normal\r\nModel Length: 69 cm in size S\r\nMaterial Outer: 65% polyester, 35% viscose\r\nModel: DE5-yzw-0087-99', 117.6, 0),
('Nike STADIUM - Sweat Jacket - Blue', 'Details for Nike STADIUM - Sweat Jacket - Blue\r\n\r\nSkillfully presents the casual STADIUM Sweat Jacket by Nike in the color blue! Her soft material made of pure cotton provides a comfortable fit. Wide knit cuffs, hood and kangaroo pockets increase the comfort factor. Extremely comfortable and perfect for the casual look, the blue STADIUM Sweat Jacket from Nike!\r\n\r\nwith hood and kangaroo pockets\r\nElastic knit cuffs\r\nRaglan sleeve inserts\r\nCare instructions: Wash at 30 degree\r\nFit: Normal\r\nModel Length: 61 cm in size S\r\nMaterial Outer: 100% cotton\r\nModel: NI1-yzw-0099-99', 299.9, 0),
('Paul Frank SCOOTER COUPLE hooded - shirt - heather gray', 'SCOOTER COUPLE details for Paul Frank hooded - shirt - heather gray\r\n\r\nGood old hoodie with fresh front print format: The SCOOTER COUPLE HOODED Hoodie by Paul Frank goes on in gray with a wonderfully colorful and plastic front print. For this, the fabric of the sweater is very soft and comfortable to wear. The hood comes with a drawstring and can be fixed so well. The uneasy stomach pouch for added comfort, cuffs on sleeves and around the waist provide protection from the cold. The gray SCOOTER COUPLE HOODED Hoodie by Paul Frank - and comfort is a sure thing!\r\n\r\nplastic front print\r\nHood with drawstring\r\nconsistent fanny pack\r\nCare instructions: Wash at 30 degrees, not suitable for drying\r\nFit: Normal\r\nModel Length: 60 cm in size S\r\nMaterial Outer: 67% polyester, 33% cotton\r\nItem number: PA7-yzw-0014-99', 135, 0),
('Replay Sweater - Green', 'Details for Replay Sweater - Green\r\n\r\nNoble - the lush green knit sweater made by Replay! The sweater is made from high quality materials and perfect finish so. That certain something gives the sweater in addition to its bright color of the deep V-neck, lace top under a tender might be good to get used. The cuffs on the arms and torso area provide the perfect fit whether in daily or festivities - the green sweater in the house Replay trims to any outfit classy!\r\n\r\nextra-wide V-neck\r\nRibbed cuffs and in the trunk\r\nCare instructions: Hand wash\r\nFit: Normal\r\nModel Length: 72 cm in size S\r\nMaterial Outer: 45% polyamide, 45% wool, 10% Angora\r\nModel: RE3-yzw 0155-99', 250, 0),
('Esprit Sweatshirt - Deep Lake melange', 'Details for Esprit Sweatshirt - Deep Lake melange\r\n\r\nIdeal for the cold season, this colorful turtleneck shirt in turquoise from Esprit, for the most part made from super soft cotton, this sweatshirt not only keeps you warm, but also offers great comfort. Thanks to the lovely turquoise color scheme, the Esprit jewel color to the gray season and is thus guaranteed new favorite piece of clothing. Design and comfort: that''s the turquoise shirt from Esprit.\r\n\r\nsoft turtleneck\r\nstretchable ribbing\r\nCare instructions: Wash at 30 degree\r\nFit: Normal\r\nModel Length: 62 cm in size S\r\nMaterial Outer: 80% viscose, 17% polyamide, 3% spandex\r\nArticle ID: ES1-yzw-0253-99', 192, 0),
('ARGYLE FINE DEPT TRICOT - Sweat Jacket - black', 'Details DEPT ARGYLE FINE TRICOT - Sweat Jacket - black\r\n\r\nA real eye-catcher: the black patterned cardigan ARGYLE FINE TRICOT DEPT. Are you looking for an exceptional piece of clothing? Then you have the black patterned cardigan extravagantly designed just right! Fields marked with floral puffy sleeves, the colorful check pattern, the gold studs and the very wide cuffs on the torso and arms make the DEPT Cardigan ARGYLE FINE TRICOT to a garment like no other that will bring you much joy! Everything but ordinary: the black patterned cardigan DEPT!\r\n\r\nvery wide cuffs\r\nextravagant design\r\nCare instructions: Wash at 30 degree\r\nFit: wide-\r\nModel Length: 51 cm in size S\r\nMaterial Outer: 100% viscose\r\nModel: DE5-yzw-0116-99', 225, 0),
('Guess STELLAR HOODIE - Sweat Jacket - Brown', 'Details for Guess STELLAR HOODIE - Sweat Jacket - Brown\r\n\r\nSporlich, elegant, extravagant - the brown hooded jacket STELLAR HOODIE by Guess. If you thought hooded jackets is only one in the gym, which has been mistaken. Guess has the club-the absolutely STELLAR HOODIE Hooded Jacket program. Of course, with hood and split kangaroo pocket, but also with many rivets and a noble-waisted cut comes STELLAR HOODIE and gives almost every outfit that extra bit of glamor. Perfect part for the perfect evening - the brown hooded jacket by Guess STELLAR HOODIE!\r\n\r\nHood with drawstring\r\nsplit kangaroo pocket\r\nCare instructions: Hand wash at 30 degree\r\nFit: Normal\r\nModel Length: 60 cm in size S\r\nMaterial Outer: 75% cotton, 25% polyester\r\nModel: GU1-yzw-0033-99', 290, 3),
('DEPT ANIMAL FLOWER - Sweatshirt - dusty olive', 'Details DEPT ANIMAL FLOWER - Sweatshirt - dusty olive\r\n\r\nThe colorful jacket ANIMAL FLOWER Dept. - feminine biker style! It comes with an allover floral and leopard prints, therefore, does not too obtrusive. The rough cut, we walked through the soft material to a very feminine piece of clothing. Two zipper front pockets and shoulder flaps make the look perfect. Unusual - the colorful jacket Dept. ANIMAL FLOWER!\r\n\r\nside zip\r\nFront zippered pockets\r\nCare instructions: Hand wash\r\nLength: Short\r\nFit: Narrow\r\nModel Length: 49 cm in size S\r\nSleeve length: 63 cm in size S\r\nMaterial Outer: 97% polyester, 3% spandex\r\nModel: DE5-yzw-0114-99', 270, 5),
('Kookai Jumper - sweater - white', 'Details for Kookai Jumper - sweater - white\r\n\r\nSparkling - the knitting sweaters JUMPER by Kookai in white. This sweater glitters in the truest sense of the word, because the white material mix was covered with all kinds of silver sequins, which provide great light effects. Beautiful are the solid cuffs and wide collar. Please notice - with the knit sweater jumper by Kookai in white.\r\n\r\ninterspersed with sequins\r\nSleeve length: 47 cm in size XS\r\nCare instructions: machine wash at 30 degree, not suitable dryer\r\nFit: Normal\r\nModel Length: 53 cm in size XS\r\nMaterial Outer: 34% acrylic, 34% polyester, 25% mohair, 7% wool\r\nItem number: KO1-yzw-0108-99', 199, 0),
('Bjorkvin PARIS-Hoody - Grey melange', 'Details for Bjorkvin PARIS-Hoody - Grey melange\r\n\r\nDanish Design! The light gray PARIS Hoody from Danish label Bjorkvin is a tribute to the city of love. The Eiffel Tower is printed in black on the hoody. Also found on the light gray hoody PARIS Bjorkvin a purple ''Paris'' logo. Another stylish detail are the birds fluttering around the tower in comic style, which were printed on the hoody. Denmark is taking on France - the helllgraue PARIS hoody Bjorkvin!\r\n\r\ngray-flecked\r\nHooded\r\nLabel embroidered in purple on the hood\r\nCare instructions: machine wash at 30 degree, not suitable dryer\r\nFit: Normal\r\nModel length: 61cm in size S\r\nMaterial Outer: 80% cotton, 20% polyester\r\nModel: BJ1-yzw-0078-99', 235, 5),
('Billabong Biwo - sweatshirt - black', 'I love doing what I want - a clear statement to the black share Biwo hoodie from Billabong. The extremely reliable and above all, super comfy sweater stands out primarily for its provocative print and formulates a clear mission: make your own decisions and to listen to anyone else. For all the rebels: the Billabong hoodie Biwo in black.\r\n\r\ncooler Print\r\nside pockets\r\nCare instructions: Wash at 30 degree\r\nFit: wide-\r\nModel Length: 66 cm in size M\r\nMaterial Outer: 80% cotton, 20% polyester\r\nModel: BI7-yzw-0025-99', 135, 5),
('Only MANDI - Sweaters - eggnog & black', 'Details for Only MANDI - Sweaters - eggnog / black\r\n\r\nMANDI a knitted dress in beige / brown from Only, which comes in a stylish Norwegian pattern. Very great design again from the House Only. The mix of sweaters and dress a very good mix. The slim cut to fit perfectly and emphasizes the feminine silhouette. Applause for this fine knit dress MANDI Beige / Brown by Only.\r\n\r\nslim cut\r\nKnitted Dress\r\nCare instructions: Wash at 30 degree\r\nFit: Narrow\r\nModel Length: 86 cm in size S\r\nMaterial Outer: 100% acrylic\r\nModel: ON321A002-003', 190, 0);

-- --------------------------------------------------------

--
-- Table structure for table `Womens_Jeans`
--

CREATE TABLE IF NOT EXISTS `Womens_Jeans` (
  `item_Name` varchar(255) NOT NULL,
  `item_Description` text NOT NULL,
  `item_Price` double NOT NULL,
  `rating_Value` int(11) NOT NULL,
  PRIMARY KEY (`item_Name`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `Womens_Jeans`
--

INSERT INTO `Womens_Jeans` (`item_Name`, `item_Description`, `item_Price`, `rating_Value`) VALUES
('Meltin Pot MELIA - jeans - denim', 'Details for Meltin Pot MELIA - jeans - denim\r\n\r\nClassically beautiful - the new jeans MELIA from Meltin ''Pot in Blue. The soft stretch denim fits in perfectly with the body and creates great curves. Bright seams accentuate this perfect cut and the fresh style. By the classic 5-pocket style, the beautiful Stone-Washed-washing and the straight-cut trousers, jeans is absolutely suitable for everyday use and fits any outfit: A pair of jeans with charisma - the new MELIA from Meltin ''Pot!\r\n\r\n5-pocket style\r\nstone washed\r\nstretchy\r\nCare instructions: Wash at 40 degree, not suitable dryer\r\nFit: Normal\r\nInseam: 80 cm for size 28/32\r\nOuter leg length: 100 cm for size 28/32\r\nWaist: low\r\nMaterial Outer: 98% cotton, 2% spandex\r\nArticle ID: ME5-yzw-0006-99\r\n', 199, 0),
('LTB CHLOE - Jeans', 'Details for LTB CHLOE - Jeans -\r\n\r\nStylish and relaxed - so you can describe the look of blue jeans from LTB CHLOE best. Zippers on the legs and on the side of the pants are a real eye-catcher. Another highlight of blue jeans from LTB CHLOE is the checkered cloth on the inside of the pockets, which flashes out a bit. The pants can be cut by their unique style, both casual and elegant. A must-have for denim lovers - the blue jeans from LTB CHLOE!\r\n\r\nrelaxed slim fit\r\nButtons and rivets with embossed label\r\nFit: Normal\r\nInseam: 69 cm for size 27/30\r\nOuter leg length: 88 cm for size 27/30\r\nBody height: normal\r\nMaterial Outer: 98% cotton, 2% spandex\r\nModel: LT1-yzw 0036-99', 170, 0),
('Vila Chino - blue', 'Details Vila Chino - blue\r\n\r\nThe jeans in the style of Chino Vila - the current trend is transmitted following the announced cut now on jeans. The slanted pockets and the width at the top of the typical characteristics, as here, unlike the classic chino pants, his legs are back to narrow down. Cool and trendy, the blue jeans in the style of Chino Vila!\r\n\r\nCustom Fit\r\nChino style with slanted pockets\r\nCare instructions: machine wash 30 degree, not suitable dryer\r\nFit: Normal\r\nInseam: 79 inches in size S\r\nOuter leg length: 104 cm in size S\r\nBody height: normal\r\nMaterial Outer: 98% cotton, 2% spandex\r\nModel: V1021B003-902', 180, 0),
('Mavi Olivia - jeans - rinsed bright', 'Details for Mavi OLIVIA - jeans - rinsed bright\r\n\r\nWith hip-wash stone-washed jeans presents itself OLIVIA Mavi! The jeans with straight leg cut has slight creases at the thigh and two back patch pockets with small knobs and pretty decorative stitching. Always a hit: the jeans from Mavi Olivia!\r\n\r\nStone washed\r\nStraight Leg\r\n5-pocket style\r\nCare instructions: Wash at 30 degree, not suitable dryer\r\nFit: Normal\r\nInseam: 85 cm for size 27/34\r\nOuter leg length: 108 cm for size 27/34\r\nWaist: low\r\nMaterial Outer: 74% cotton, 26% spandex\r\nArticle ID: MA6-yzw-0085-99', 270, 0),
('Vila ATIKA - jeans - denim', 'Details Vila ATIKA - jeans - denim\r\n\r\nThe new jeans ATIKA Vila in blue: casual bootcut-style! The new jeans from Vila is in the trendy pleats look so great in a denim color. Orange and yellow Nahtee stand out nice and round off the design perfectly. The new ATIKA Bootcut Jeans from Vila: A must-have!\r\n\r\nCrease\r\norange and yellow stitching\r\nBootcut\r\nCare instructions: Machine wash at 40 degree, not suitable dryer\r\nFit: Normal\r\nInseam: 80cm in size 32\r\nOuter leg length: 100cm in size 32\r\nBody height: normal\r\nMaterial Outer: 98% cotton, 2% spandex\r\nModel: V1021B001-902', 190, 0),
('Replay Jeans - blue', 'Details for Replay jeans - blue\r\n\r\nA cool companion for any occasion: the blue jeans from Replay. Not only the design of blue jeans thrilled the comfort of wear convinced all along the line. Thanks to the stretch portion nestles the Replay jeans perfectly to the leg, guaranteeing optimum fit. The strong ablutions, make the cut and straight leg 5 Pocket Denim Jeans these pants actually a prototype. An absolute must-have: the blue jeans by Replay!\r\n\r\nStretch-share\r\nStraight Leg cut\r\nCare instructions: Wash at 30 degree\r\nFit: Normal\r\nInseam: 82 cm for size 28/32\r\nOuter leg length: 98 cm for size 28/32\r\nBody height: normal\r\nMaterial Outer: 98% cotton, 2% spandex\r\nModel: RE3-yzw 0122-99', 230, 0),
('LTB VALERIE RIVIERA - jeans - denim', 'Details for LTB VALERIE RIVIERA - jeans - denim\r\n\r\nTrendy and chic - the denim jeans from LTB VALERIE RIVIERA. This relaxed bootcut jeans with a real eye-catcher. In relaxing used look and are equipped with jeans-typical attributes such as 5-pocket denim, heavy wash and Buffie, playing with these pants in the first division. Rivets on front pockets and contrasting stitching on the whole court to make the design complete. Cool look - with the denim jeans from LTB VALERIE RIVIERA in blue!\r\n\r\nBootcut\r\nDistressed\r\nCare instructions: Wash at 40 degree\r\nFit: Normal\r\nInseam: 82 cm for size 27/32\r\nOuter leg length: 104 cm for size 27/32\r\nBody height: normal\r\nMaterial Outer: 98% cotton, 2% spandex\r\nModel: LT1-yzw 0008-99', 260, 5),
('JUSTINE Guess - Jeans-eagle', 'JUSTINE Details for Guess - Jeans-eagle\r\n\r\nStylishly elegant with the new Guess Jeans JUSTINE in blue! The deep-seated Skinny Leg Jeans JUSTINE destroyed by the effects is stretchable and lightening in the upper range of very stylish. The unusual occupied with rhinestones back trouser pockets, as well as provided with the logo button. The new highlight of the luxury Laben Guess - JUSTINE the jeans in blue!\r\n\r\nStretch Material available\r\ncolored lining on the inside waistband\r\nFit: Narrow\r\nInseam: 78\r\nOuter leg length: 94 cm in size 27\r\nWaist: low\r\nMaterial Outer: 98% cotton, 2% elastane\r\nModel: GU1-yzw-0022-99', 360, 0),
('Mavi Lindy - jeans - dark comet', 'Details for Mavi Lindy - jeans - dark comet\r\n\r\nThe timeless Skinny Jeans Mavi Lindy from the house in blue comes from the hip Washed-look! The hip-deep 5-pocket form with short zipper fly gives the jeans a classic look LINDY. The soft material conforms perfectly to Jean to the body and brings the wearer comfortable through the day. The new blue jeans by Mavi in LINDY spices up any outfit look more and is a must-have for Jean lovers!\r\n\r\n5-pocket system\r\nslight used look\r\nCare instructions: Wash at 30 degree\r\nFit: Narrow\r\nInseam: 79 cm for size 27/32\r\nOuter leg length: 98 cm for size 27/32\r\nBody height: normal\r\nMaterial Outer: 98% cotton, 2% spandex\r\nArticle ID: MA6-yzw-0065-99\r\n', 345, 0),
('Fornarina Jeans - Blue', 'Details for Fornarina jeans - blue\r\n\r\nHere''s what to look: is the blue jeans by Fornarina, as expected from this fashion designer otherwise, bold accents. The hem of the two front pockets with rock chrome studs, while the rear is only one bag was equipped accordingly. Adjust the legs with broken used effects are provided. The blue jeans by Fornarina can certainly put in the category of ''the rage'' - Wow!\r\n\r\nPockets inside dotted blue black\r\nGathered fabric at the thigh\r\nsmall zip\r\nFrans effect on the belt loops\r\nCare instructions: Hand wash at 30 degrees, not suitable dryer\r\nFit: Normal\r\nInseam: 76 cm for size 28\r\nForeign leg length: 96 cm for size 28\r\nBody height: normal\r\nMaterial Outer: 89% cotton, 11% polyester\r\nModel: FO1-yzw-0086-99', 355, 0),
('Nudie TIGH LONG JOHN - jeans - worn shady', 'Details for Nudie TIGH LONG JOHN - jeans - worn shady\r\n\r\nLove at first sight: LONG JOHN TIGH in blue jeans from Nudie. These jeans meets all the demands that are placed on a new favorite pants. Stretch, low waist, slim fit and a casual washing LONG JOHN TIGH make a real must-have, which emphasizes the character skillfully. The most attractive denim-style: with the blue jeans by Nudie TIGH LONG JOHN!\r\n\r\nStretch\r\nyellow decorative seams\r\nCare instructions: Wash at 40 degree\r\nFit: Narrow\r\nInseam: 86 cm for size 26/34\r\nOuter leg length: 106 cm for size 26/34\r\nWaist: low\r\nMaterial Outer: 98% cotton, 2% elastane\r\nModel: NU2-yzw-0005-99', 270, 0),
('Pepe Jeans BOOTCUT JOULE X67 - jeans - medium shade', 'Details for Pepe Jeans BOOTCUT JOULE X67 - jeans - medium shade\r\n\r\nJOULE 5-pocket style made by Pepe Jeans - tighten and relax! Bright decorative stitching give the dark blue jeans their stylish look that gives you just cut both leisure and fitness for office and makes it a real life companion. For women who know what they want - the JOULE in blue jeans by Pepe Jeans!\r\n\r\nBootcut\r\nLow Waist\r\nInner material: 50% cotton, 50% polyester\r\nCare instructions: machine wash at 40 degree, not suitable dryer\r\nFit: Normal\r\nInseam: 81 cm for size 27/32\r\nOuter leg length: 101 cm for size 27/32\r\nWaist: low\r\nMaterial Outer: 98% cotton, 2% spandex\r\nModel: PE1-yzw-0079-99', 390, 5),
('Mavi Lindy - blue jeans', 'Details for Mavi Lindy - blue jeans\r\n\r\nHot - the blue skinny jeans by Mavi Lindy! This pant with low rise-Fit comes in dark blue and marked with washes. 5-pocket denim and a short zipper make for a perfect jeans feel and subtle stitching on the back pockets and share feminine accents. The small spandex content make for a really bright, the seat of Mavi Jeans Lindy in blue - a great pants!\r\n\r\nLow Rise\r\nSlim Fit\r\nCare instructions: machine wash at 40 degree, not suitable dryer\r\nFit: Narrow\r\nInseam: 83 cm for size 27/32\r\nOuter leg length: 105 cm for size 27/32\r\nWaist: low\r\nMaterial Outer: 98% cotton, 2% elastane\r\nArticle ID: MA6-yzw-0094-99', 268, 0),
('Mavi Olivia - Jeans - deep cool', 'Details for Mavi OLIVIA - Jeans - deep cool\r\n\r\nThe classic straight leg jeans in dark blue OLIVIA with subtle washes! The highlight of these jeans are the intricate stitching on the back pocket and the classic 5-pocket style. The soft material conforms perfectly to Jean to the body and brings the wearer comfortable through the day. For Jean lovers - the new jeans from Mavi Olivia in blue!\r\n\r\n5-pocket style\r\nCare instructions: Wash at 30 degree\r\nFit: Normal\r\nInside length: 103 cm for size 27/32\r\nOuter leg length: 80 cm for size 27/32\r\nWaist: low\r\nMaterial Outer: 98% cotton, 2% elastane\r\nArticle ID: MA6-yzw-0096-99', 350, 5);

-- --------------------------------------------------------

--
-- Table structure for table `Womens_ShirtsAndTops`
--

CREATE TABLE IF NOT EXISTS `Womens_ShirtsAndTops` (
  `item_Name` varchar(255) NOT NULL,
  `item_Description` text NOT NULL,
  `item_Price` double NOT NULL,
  `rating_Value` int(11) NOT NULL,
  PRIMARY KEY (`item_Name`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `Womens_ShirtsAndTops`
--

INSERT INTO `Womens_ShirtsAndTops` (`item_Name`, `item_Description`, `item_Price`, `rating_Value`) VALUES
('Esprit shirt - black', 'Details for Esprit shirt - black\r\nThere is more to it - the new Shirt in black and white from Esprit! The shirt has comfortable inside or a white top that protects unpopular views and emphasizes the sporty look. With small buttons and a gathering at chest height, it still looks feminine and delicate. Perfect for a casual jeans look - the black Shirt from Esprit!\r\nbeen revised Top Placket\r\nCare instructions: 40 degree machine wash, not suitable dryer\r\nFit: Normal\r\nModel Length: 61 cm in size S\r\nMaterial Outer: 100% cotton\r\nArticle ID: ES1-yzw-0206-99', 280, 4),
('Vero Moda CHANCE - T-Shirt - nougat', 'Details for Vero Moda CHANCE - T-Shirt - nougat\r\n\r\nLovingly decorated - the brown top from Vero Moda CHANCE. Splendid patterns stand out from here on the chest and shoulders from the brown material and provide engaging accents. While ensuring the airy material and the wide collar for comfort and ruffles offer under the breast and back unnecessary elements. For romantics - the brown top from Vero Moda CHANCE.\r\n\r\nLining: 100% polyester\r\nRuffles\r\nCare instructions: machine wash at 30 degree, not suitable dryer\r\nFit: Normal\r\nModel Length: 65 cm in size S\r\nMaterial Outer: 100% polyester\r\nModel: VE1-yzw-0756-99', 235, 0),
('Margit Brandt SHANTI - Shirt - castle rock', 'Details for Margit Brandt SHANTI - Shirt - castle rock\r\n\r\nSHANTI Longlseeve in gray Margaret Brandt. The intersection of the soft upper part makes it suitable for everyday use and stylish at the same time. The clear cut with round neck is the same color fabric application really refined. Shall have the top - despite the high round neckline - while on a detail in waterfall look. The mix of wool and viscose provides comfort. Comfortable and fashionable - SHANTI in gray, the Longsleeve by Margaret Brandt.\r\n\r\nwonderfully soft fabric\r\nrefined detail\r\nCare Instructions: Cleaning\r\nLength: Medium\r\nModel Length: 81 cm in size S\r\nMaterial Outer: 55% wool, 45% viscose\r\nModel: M11-yzw 0053-99', 250, 0),
('ESPRIT Collection Longtop - grey', 'Details for ESPRIT Collection Longtop - black\r\n\r\nAbsolutely chic: the light gray Longtop of Esprit! With a cool application, the light gray Longtop presents falling from soft viscose as a great eye-catcher. The straight-cut top comes with a scoop neck and is closed back up. Combines great in any case: the light gray top from Esprit!\r\n\r\nsewn rhinestones\r\nCare instructions: machine wash at 30 degree, not suitable dryer\r\nLength: Long\r\nModel Length: 68 cm in size S\r\nMaterial Outer: 100% viscose\r\nModel: ES4-yzw 0085-99', 199, 5),
('Killah Shirt - white', 'Details for Killah T-Shirt - white\r\n\r\nThe look of the 50''s now in our time: the black dotted Longsleeve Killah. With ribbed crew neck and sweet polka dots, the white longsleeve is absolutely a trend. Made of cotton and spandex, is impressive not only design but also the high comfort. Perfect fit and high wearing comfort, the Killah Shirt in White guaranteed new favorite. Who can resist that yet - T-Shirt in White by Killah!\r\n\r\nPolka Dots\r\nsoft material\r\nCare instructions: machine wash 40 degree\r\nFit: Normal\r\nModel Length: 59 cm in size S\r\nMaterial Outer: 95% cotton, 5% elastane\r\nModel: KI2-yzw-0120-99', 230, 0),
('Hilfiger Denim LARAN - Shirt - Grey', 'Details for Tommy Hilfiger LARAN - Shirt - Grey\r\n\r\nCreepy beautiful: the gray longsleeve LARAN from Tommy Hilfiger! Classic cut the gray longsleeve by Hilfiger Denim is made of elastic cotton with crew neck. Super is the eerily beautiful personalized logo printed from skeletons and pink floral pattern on the chest of LARAN. A highlight: the gray longsleeve LARAN from Tommy Hilfiger!\r\n\r\nSchurig nice logo print\r\nCrew neck\r\nCare instructions: Machine wash at 30 degree\r\nFit: Narrow\r\nModel length: 60cm in size S\r\nMaterial Outer: 65% polyester, 35% cotton\r\nModel: HI121F00T-102', 200, 0),
('Cream FLORENCE - Shirt - Smoked Pearl', 'Details for Cream FLORENCE - Shirt - Smoked Pearl\r\n\r\nFLORENCE - will enchant its wearer! The long-sleeved shirt FLORENCE out of the house in Grey Cream of soft, flowing fabric is very comfortable to wear on the skin and jazzes up any outfit. The beautiful top of the shirt in gray FLORENCE Cream makes an absolutely wonderful and extravagant Basic.\r\n\r\nsoft flowing material\r\nLace\r\nCare instructions: Wash at 30 degree\r\nFit: Normal\r\nModel Length: 75 cm in size S\r\nMaterial Outer: 92% viscose, 8% spandex\r\nModel: CR2-yzw 0091-99', 290, 0),
('Vila POWE - Shirt - dull rose & sand shell', 'Details Vila POWE - Shirt - dull rose / sand shell\r\n\r\nOrnaments in muted shades of brown - the Top POWE Vila in brown. Puffed sleeves, a nice waist and a wide collar make POWE attractive. Beautiful are the half -sleeves. Feminine elegance - the brown POWE Top of Vila.\r\n\r\nFitted\r\npuffed sleeves\r\nSleeve length: 52 cm in size S\r\nCare instructions: machine wash at 30 degree, not suitable dryer\r\nFit: Normal\r\nModel Length: 66 cm in size S\r\nMaterial Outer: 100% cotton\r\nModel: V1021F00E-401', 225, 0),
('Esprit - Shirt - pale blue', 'Details for Esprit - shirt - pale blue\r\n\r\nThere is more to it - the new blue-Shirt in white from Esprit! The blue shirt is still inside a white top that protects unpopular views and emphasizes the sporty look. With small buttons and a gathering at chest height, it still looks feminine and delicate. Perfect for a casual jeans look - the Blue Shirt from Esprit!\r\n\r\nbeen revised Top\r\nPlacket\r\nCare instructions: Wash at 40 degree, not suitable dryer\r\nFit: Normal\r\nModel Length: 61 cm in size S\r\nMaterial Outer: 100% cotton\r\nArticle ID: ES1-yzw-0207-99', 190, 0),
('DEPT CAMOUFLAGE BUTTERFLY - shirt - dusty olive', 'Details DEPT CAMOUFLAGE BUTTERFLY - shirt - dusty olive\r\n\r\nThe dark green shirt CAMOUFLAGE BUTTERFLY Dept. - exceptionally adorable! It is a feminine cut narrow and therefore with sleeves. The interesting allover butterfly patterns, and cheeky gathering to make the front is a real favorite. Summer pattern cheers on the rainy autumn, but fits perfectly in color - with the shirt CAMOUFLAGE BUTTERFLY Dept. in dark green!\r\n\r\nRuffles on the front\r\nsoft cuffs\r\nDept. small-bow in the neck\r\nCare instructions: Hand wash\r\nFit: Narrow\r\nModel Length: 62 cm in size S\r\nMaterial Outer: 97% polyester, 3%  spandex\r\nModel: DE5-yzw-0091-99', 275, 0),
('Desigual Shirt - Multicolor', 'Details for Desigual Shirt - Multicolor\r\n\r\nBoring is quite different - this Longtop Desigual can be worn in a hundred different species and over again, there are casual look the finishing touches. With relatively wide round neckline, long sleeves and a sexy fitted shape that looks like a Longtop 60s Ibiza holiday and promises the very large style freedom. Particularly striking is of course, the all-over pattern, just cool, retro and very exciting that Longtop Desigual!\r\n\r\nRound neck\r\nAllover pattern\r\nCare instructions: Wash at 30 degree\r\nFit: Normal\r\nModel Length: 78 cm in size S\r\nMaterial Outer: 75% viscose, 25% cotton\r\nModel: DE1-yzw-0108-99', 299, 5),
('Vero Moda NEW RATLI LS V-NECK - shirt - white', 'Details for Vero Moda NEW RATLI LS V-NECK - shirt - white\r\n\r\nSimply the best - NEW RATLI LS V-NECK, white shirt of high quality cotton from Vero Moda! The centerpiece of the trendsetters is occupied with the top section. But the feminine cut can be seen, he caresses the waist, making it a real eye catcher. NEW RATLI LS V-NECK, white shirt by Vero Moda!\r\n\r\nNeckline trimmed\r\nfeminine waistline\r\nCare: machine wash at 40 degree \r\nFit: Narrow\r\nModel Length: 55 cm in size S\r\nMaterial Outer: 100% cotton\r\nModel: VE1-yzw-0745-99', 259, 5),
('Coffee Shirt - steel melange', 'Details for coffee Shirt - steel melange\r\n\r\nCoffee comes here so long with a cool shirt. Stoffraffungen in the middle of the front and two side pockets make the casual look of long shirts. The half sleeves and round neck round out the casual exterior of the shirts. If in any wardrobe is missing - the gray long shirt of coffee!\r\n\r\nStoffraffung on the front\r\nCrew neck\r\n2 side pockets\r\nSleeve length: 47 cm in size S\r\nCare instructions: 40 degree machine wash, not suitable dryer\r\nFit: Normal\r\nModel Length: 88 cm in size S\r\nMaterial Outer: 100% cotton\r\nModel: KA3-yzw-0083-99', 225, 5);
